--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_head
local Image_head = ccui.ImageView:create()
Image_head:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/match/hall_match_plist2.plist")
Image_head:loadTexture("match_mate_bg_header2.png",1)
Image_head:setLayoutComponentEnabled(true)
Image_head:setName("Image_head")
Image_head:setTag(753)
Image_head:setCascadeColorEnabled(true)
Image_head:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_head)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(-60.0000)
layout:setRightMargin(-60.0000)
layout:setTopMargin(-60.0000)
layout:setBottomMargin(-60.0000)
Node:addChild(Image_head)

--Create match_mate
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/match/hall_match_plist2.plist")
local match_mate = cc.Sprite:createWithSpriteFrameName("match_mate_bg_header2.png")
match_mate:setName("match_mate")
match_mate:setTag(151)
match_mate:setCascadeColorEnabled(true)
match_mate:setCascadeOpacityEnabled(true)
match_mate:setPosition(60.0000, 60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(match_mate)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 120.0000, height = 120.0000})
match_mate:setBlendFunc({src = 1, dst = 771})
Image_head:addChild(match_mate)

--Create match_check
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/match/hall_match_plist2.plist")
local match_check = cc.Sprite:createWithSpriteFrameName("match_mate_friendtag.png")
match_check:setName("match_check")
match_check:setTag(150)
match_check:setCascadeColorEnabled(true)
match_check:setCascadeOpacityEnabled(true)
match_check:setPosition(60.3401, 15.3642)
layout = ccui.LayoutComponent:bindLayoutComponent(match_check)
layout:setPositionPercentX(0.5028)
layout:setPositionPercentY(0.1280)
layout:setPercentWidth(0.4000)
layout:setPercentHeight(0.4000)
layout:setSize({width = 48.0000, height = 48.0000})
layout:setLeftMargin(36.3401)
layout:setRightMargin(35.6599)
layout:setTopMargin(80.6358)
layout:setBottomMargin(-8.6358)
match_check:setBlendFunc({src = 1, dst = 771})
Image_head:addChild(match_check)

--Create Text_signup
local Text_signup = ccui.Text:create()
Text_signup:ignoreContentAdaptWithSize(true)
Text_signup:setTextAreaSize({width = 0, height = 0})
Text_signup:setFontName("FZZhengHeiS-B-GB.ttf")
Text_signup:setFontSize(30)
Text_signup:setString([[UserName]])
Text_signup:setLayoutComponentEnabled(true)
Text_signup:setName("Text_signup")
Text_signup:setTag(232)
Text_signup:setCascadeColorEnabled(true)
Text_signup:setCascadeOpacityEnabled(true)
Text_signup:setPosition(4.1641, -117.2487)
Text_signup:setTextColor({r = 244, g = 255, b = 229})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_signup)
layout:setSize({width = 187.0000, height = 37.0000})
layout:setLeftMargin(-89.3359)
layout:setRightMargin(-97.6641)
layout:setTopMargin(98.7487)
layout:setBottomMargin(-135.7487)
Node:addChild(Text_signup)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

