cc.exports.HotUpdateCfg = {}

HotUpdateCfg.innerEventComponent = nil
HotUpdateCfg.InnerEvents = {
	UPGRADE_NO_HOTUPDATE = "UPGRADE_NO_HOTUPDATE", --没有更新
	UPGRADE_PACKAGE_UPDATE = "UPGRADE_PACKAGE_UPDATE", --整包更新
	
	UPGRADE_DOWNLOAD_ERROR = "UPGRADE_DOWNLOAD_ERROR", --更新失败
	UPGRADE_START_SILENCE_DOWNLOAD = "UPGRADE_START_SILENCE_DOWNLOAD",--开始静默下载
	UPGRADE_DOWNLOADING_PROGRESS = "UPGRADE_DOWNLOADING_PROGRESS", --下载进度
	UPGRADE_FINISH_MODULE_DOWNLOAD = "UPGRADE_FINISH_MODULE_DOWNLOAD", --模块下载完成
	UPGRADE_FINISH_DOWNLOAD = "UPGRADE_FINISH_DOWNLOAD", --下载完成
	UPGRADE_UNZIPING_PROGRESS = "UPGRADE_UNZIPING_PROGRESS", --解压开始
	UPGRADE_FINISH_DOWNLOAD_UNZIP = "UPGRADE_FINISH_DOWNLOAD_UNZIP", --下载解压完成
	UPGRADE_GETREMOVE_FILEZIE = "UPGRADE_GETREMOVE_FILEZIE", --获取远程下载文件的大小
	UPGRADE_RESDOWNLOADADDR_MANUAL_CALLBACK = "UPGRADE_RESDOWNLOADADDR_MANUAL_CALLBACK", --资源下载地址获取到后的回调地址
	UPGRADE_RESDOWNLOADADDR_SILENT_CALLBACK = "UPGRADE_RESDOWNLOADADDR_SILENT_CALLBACK",--资源下载地址获取到后的回调地址
	UPGRADE_FINISH_SILENCE_DOWNLOAD = "UPGRADE_FINISH_SILENCE_DOWNLOAD", --停止静默下载
	UPGRADE_FINISH_HOT_UPDATE = "UPGRADE_FINISH_HOT_UPDATE", --lua热更完成
	UPGRADE_UNZIP_MODULE_SUCCESS = "UPGRADE_UNZIP_MODULE_SUCCESS", --解压模块完成
	UPGRADE_CHECK_MODULE_EXISTS = "UPGRADE_CHECK_MODULE_EXISTS", --监测资源是否存在
	UPGRADE_FINISH_DOWNLOAD_UNZIP_TOLAYER = "UPGRADE_FINISH_DOWNLOAD_UNZIP_TOLAYER", --下载解压完成UI响应事件
	
}

HotUpdateCfg.eventMap = {
	{UpgradeEventId.UPGRADE_DOWNLOAD_ERROR,HotUpdateCfg.InnerEvents.UPGRADE_DOWNLOAD_ERROR},
	{UpgradeEventId.UPGRADE_START_SILENCE_DOWNLOAD,HotUpdateCfg.InnerEvents.UPGRADE_START_SILENCE_DOWNLOAD},
	{UpgradeEventId.UPGRADE_DOWNLOADING_PROGRESS,HotUpdateCfg.InnerEvents.UPGRADE_DOWNLOADING_PROGRESS},
	{UpgradeEventId.UPGRADE_FINISH_MODULE_DOWNLOAD,HotUpdateCfg.InnerEvents.UPGRADE_FINISH_MODULE_DOWNLOAD},
	{UpgradeEventId.UPGRADE_FINISH_DOWNLOAD,HotUpdateCfg.InnerEvents.UPGRADE_FINISH_DOWNLOAD},
	{UpgradeEventId.UPGRADE_UNZIPING_PROGRESS,HotUpdateCfg.InnerEvents.UPGRADE_UNZIPING_PROGRESS},
	{UpgradeEventId.UPGRADE_FINISH_DOWNLOAD_UNZIP,HotUpdateCfg.InnerEvents.UPGRADE_FINISH_DOWNLOAD_UNZIP},
	{UpgradeEventId.UPGRADE_GETREMOVE_FILEZIE,HotUpdateCfg.InnerEvents.UPGRADE_GETREMOVE_FILEZIE},
	{UpgradeEventId.UPGRADE_RESDOWNLOADADDR_MANUAL_CALLBACK,HotUpdateCfg.InnerEvents.UPGRADE_RESDOWNLOADADDR_MANUAL_CALLBACK},
	{UpgradeEventId.UPGRADE_RESDOWNLOADADDR_SILENT_CALLBACK,HotUpdateCfg.InnerEvents.UPGRADE_RESDOWNLOADADDR_SILENT_CALLBACK},
	{UpgradeEventId.UPGRADE_FINISH_SILENCE_DOWNLOAD,HotUpdateCfg.InnerEvents.UPGRADE_FINISH_SILENCE_DOWNLOAD},
	{UpgradeEventId.UPGRADE_FINISH_HOT_UPDATE,HotUpdateCfg.InnerEvents.UPGRADE_FINISH_HOT_UPDATE},
	{UpgradeEventId.UPGRADE_UNZIP_MODULE_SUCCESS,HotUpdateCfg.InnerEvents.UPGRADE_UNZIP_MODULE_SUCCESS},
	{UpgradeEventId.UPGRADE_CHECK_MODULE_EXISTS,HotUpdateCfg.InnerEvents.UPGRADE_CHECK_MODULE_EXISTS},
	{UpgradeEventId.UPGRADE_FINISH_DOWNLOAD_UNZIP_TOLAYER,HotUpdateCfg.InnerEvents.UPGRADE_FINISH_DOWNLOAD_UNZIP_TOLAYER},
	
}
function HotUpdateCfg.getEventById(eid)
	local eventName = nil
	for _,v in pairs(HotUpdateCfg.eventMap) do
		if v[1]==eid then
			eventName = v[2]
		end
	end
	return eventName
end
--请求资源类型，1 zip模块文件  2 资源的差分文件
HotUpdateCfg.sourceType = {
	ModuleZip = 1,
	ResDiff = 2,
}
--热更下载方式
HotUpdateCfg.downloadType = {
	SilenceDownload = 0,--静默
    ManualDownload = 1,	--手动
}
