cc.exports.UpgradeEventId = {
	UPGRADE_DOWNLOAD_ERROR = 0, --更新失败
	UPGRADE_START_SILENCE_DOWNLOAD = 1,--开始静默下载
	UPGRADE_DOWNLOADING_PROGRESS = 2, --下载进度
	UPGRADE_FINISH_MODULE_DOWNLOAD = 3, --模块下载完成
	UPGRADE_FINISH_DOWNLOAD = 4, --下载完成
	UPGRADE_UNZIPING_PROGRESS = 5, --解压开始
	UPGRADE_FINISH_DOWNLOAD_UNZIP = 6, --下载解压完成
	UPGRADE_GETREMOVE_FILEZIE = 7, --获取远程下载文件的大小
	UPGRADE_RESDOWNLOADADDR_MANUAL_CALLBACK = 8, --资源下载地址获取到后的回调地址
	UPGRADE_RESDOWNLOADADDR_SILENT_CALLBACK = 9,--资源下载地址获取到后的回调地址
	UPGRADE_FINISH_SILENCE_DOWNLOAD = 10, --停止静默下载
	UPGRADE_FINISH_HOT_UPDATE = 11, --lua热更完成
	UPGRADE_UNZIP_MODULE_SUCCESS = 12, --解压模块完成
	UPGRADE_CHECK_MODULE_EXISTS = 13, --监测资源是否存在
	UPGRADE_FINISH_DOWNLOAD_UNZIP_TOLAYER = 14, --下载解压完成UI响应事件
	
}
