--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1020.0000, height = 809.0000})

--Create phone_verify
local phone_verify = ccui.ImageView:create()
phone_verify:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/account/account_plist.plist")
phone_verify:loadTexture("account_icon_phone.png",1)
phone_verify:setLayoutComponentEnabled(true)
phone_verify:setName("phone_verify")
phone_verify:setTag(93)
phone_verify:setCascadeColorEnabled(true)
phone_verify:setCascadeOpacityEnabled(true)
phone_verify:setPosition(215.4459, 631.4061)
layout = ccui.LayoutComponent:bindLayoutComponent(phone_verify)
layout:setPositionPercentX(0.2112)
layout:setPositionPercentY(0.7805)
layout:setPercentWidth(0.0363)
layout:setPercentHeight(0.0593)
layout:setSize({width = 37.0000, height = 48.0000})
layout:setLeftMargin(196.9459)
layout:setRightMargin(786.0541)
layout:setTopMargin(153.5939)
layout:setBottomMargin(607.4061)
Layer:addChild(phone_verify)

--Create phone_txt_verify
local phone_txt_verify = ccui.Text:create()
phone_txt_verify:ignoreContentAdaptWithSize(true)
phone_txt_verify:setTextAreaSize({width = 0, height = 0})
phone_txt_verify:setFontSize(48)
phone_txt_verify:setString([[您的手机号码:88888888888]])
phone_txt_verify:setLayoutComponentEnabled(true)
phone_txt_verify:setName("phone_txt_verify")
phone_txt_verify:setTag(94)
phone_txt_verify:setCascadeColorEnabled(true)
phone_txt_verify:setCascadeOpacityEnabled(true)
phone_txt_verify:setAnchorPoint(0.0000, 0.5000)
phone_txt_verify:setPosition(53.1464, 23.0674)
phone_txt_verify:setRotationSkewY(-0.0035)
phone_txt_verify:setTextColor({r = 255, g = 163, b = 20})
layout = ccui.LayoutComponent:bindLayoutComponent(phone_txt_verify)
layout:setPositionPercentX(1.4364)
layout:setPositionPercentY(0.4806)
layout:setPercentWidth(15.5676)
layout:setPercentHeight(1.0000)
layout:setSize({width = 576.0000, height = 48.0000})
layout:setLeftMargin(53.1464)
layout:setRightMargin(-592.1464)
layout:setTopMargin(0.9326)
layout:setBottomMargin(-0.9326)
phone_verify:addChild(phone_txt_verify)

--Create phone_txt1_verify
local phone_txt1_verify = ccui.Text:create()
phone_txt1_verify:ignoreContentAdaptWithSize(true)
phone_txt1_verify:setTextAreaSize({width = 0, height = 0})
phone_txt1_verify:setFontSize(32)
phone_txt1_verify:setString([[您会收到一条带有验证码的短信，请输入验证码]])
phone_txt1_verify:setLayoutComponentEnabled(true)
phone_txt1_verify:setName("phone_txt1_verify")
phone_txt1_verify:setTag(95)
phone_txt1_verify:setCascadeColorEnabled(true)
phone_txt1_verify:setCascadeOpacityEnabled(true)
phone_txt1_verify:setPosition(510.1002, 546.0399)
phone_txt1_verify:setTextColor({r = 244, g = 255, b = 229})
layout = ccui.LayoutComponent:bindLayoutComponent(phone_txt1_verify)
layout:setPositionPercentX(0.5001)
layout:setPositionPercentY(0.6750)
layout:setPercentWidth(0.6588)
layout:setPercentHeight(0.0408)
layout:setSize({width = 672.0000, height = 33.0000})
layout:setLeftMargin(174.1002)
layout:setRightMargin(173.8998)
layout:setTopMargin(246.4601)
layout:setBottomMargin(529.5399)
Layer:addChild(phone_txt1_verify)

--Create line_verify
local line_verify = ccui.ImageView:create()
line_verify:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/account/account_plist.plist")
line_verify:loadTexture("account_line_1.png",1)
line_verify:setLayoutComponentEnabled(true)
line_verify:setName("line_verify")
line_verify:setTag(96)
line_verify:setCascadeColorEnabled(true)
line_verify:setCascadeOpacityEnabled(true)
line_verify:setPosition(510.0838, 468.8180)
layout = ccui.LayoutComponent:bindLayoutComponent(line_verify)
layout:setPositionPercentX(0.5001)
layout:setPositionPercentY(0.5795)
layout:setPercentWidth(0.8108)
layout:setPercentHeight(0.0049)
layout:setSize({width = 827.0000, height = 4.0000})
layout:setLeftMargin(96.5838)
layout:setRightMargin(96.4162)
layout:setTopMargin(338.1820)
layout:setBottomMargin(466.8180)
Layer:addChild(line_verify)

--Create bg_input_verify
local bg_input_verify = ccui.ImageView:create()
bg_input_verify:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/account/account_plist.plist")
bg_input_verify:loadTexture("account_input_3.png",1)
bg_input_verify:setLayoutComponentEnabled(true)
bg_input_verify:setName("bg_input_verify")
bg_input_verify:setTag(97)
bg_input_verify:setCascadeColorEnabled(true)
bg_input_verify:setCascadeOpacityEnabled(true)
bg_input_verify:setPosition(365.5620, 356.4612)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_input_verify)
layout:setPositionPercentX(0.3584)
layout:setPositionPercentY(0.4406)
layout:setPercentWidth(0.4931)
layout:setPercentHeight(0.1187)
layout:setSize({width = 503.0000, height = 96.0000})
layout:setLeftMargin(114.0620)
layout:setRightMargin(402.9380)
layout:setTopMargin(404.5388)
layout:setBottomMargin(308.4612)
Layer:addChild(bg_input_verify)

--Create key_verify
local key_verify = ccui.ImageView:create()
key_verify:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/account/account_plist.plist")
key_verify:loadTexture("account_icon_key.png",1)
key_verify:setLayoutComponentEnabled(true)
key_verify:setName("key_verify")
key_verify:setTag(99)
key_verify:setCascadeColorEnabled(true)
key_verify:setCascadeOpacityEnabled(true)
key_verify:setPosition(72.2720, 46.1721)
layout = ccui.LayoutComponent:bindLayoutComponent(key_verify)
layout:setPositionPercentX(0.1437)
layout:setPositionPercentY(0.4810)
layout:setPercentWidth(0.1392)
layout:setPercentHeight(0.7292)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(37.2720)
layout:setRightMargin(395.7280)
layout:setTopMargin(14.8279)
layout:setBottomMargin(11.1721)
bg_input_verify:addChild(key_verify)

--Create input_code_verify
local input_code_verify = ccui.TextField:create()
input_code_verify:ignoreContentAdaptWithSize(false)
tolua.cast(input_code_verify:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
input_code_verify:setFontSize(32)
input_code_verify:setPlaceHolder("短信验证码")
input_code_verify:setString([[]])
input_code_verify:setMaxLengthEnabled(true)
input_code_verify:setMaxLength(6)
input_code_verify:setLayoutComponentEnabled(true)
input_code_verify:setName("input_code_verify")
input_code_verify:setTag(100)
input_code_verify:setCascadeColorEnabled(true)
input_code_verify:setCascadeOpacityEnabled(true)
input_code_verify:setPosition(325.2164, 44.1715)
input_code_verify:setColor({r = 153, g = 154, b = 154})
layout = ccui.LayoutComponent:bindLayoutComponent(input_code_verify)
layout:setPositionPercentX(0.6466)
layout:setPositionPercentY(0.4601)
layout:setPercentWidth(0.5964)
layout:setPercentHeight(0.4375)
layout:setSize({width = 300.0000, height = 42.0000})
layout:setLeftMargin(175.2164)
layout:setRightMargin(27.7836)
layout:setTopMargin(30.8285)
layout:setBottomMargin(23.1715)
bg_input_verify:addChild(input_code_verify)

--Create btn_send_verify
local btn_send_verify = ccui.Button:create()
btn_send_verify:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/account/account_plist.plist")
btn_send_verify:loadTextureNormal("account_btn_send.png",1)
btn_send_verify:setTitleFontName("FZZhengHeiS-B-GB.ttf")
btn_send_verify:setTitleFontSize(30)
btn_send_verify:setTitleText("发送")
btn_send_verify:setTitleColor({r = 254, g = 255, b = 229})
btn_send_verify:setScale9Enabled(true)
btn_send_verify:setCapInsets({x = 15, y = 11, width = 228, height = 78})
btn_send_verify:setLayoutComponentEnabled(true)
btn_send_verify:setName("btn_send_verify")
btn_send_verify:setTag(98)
btn_send_verify:setCascadeColorEnabled(true)
btn_send_verify:setCascadeOpacityEnabled(true)
btn_send_verify:setPosition(781.1110, 356.4612)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_send_verify)
layout:setPositionPercentX(0.7658)
layout:setPositionPercentY(0.4406)
layout:setPercentWidth(0.2529)
layout:setPercentHeight(0.1236)
layout:setSize({width = 258.0000, height = 100.0000})
layout:setLeftMargin(652.1110)
layout:setRightMargin(109.8890)
layout:setTopMargin(402.5388)
layout:setBottomMargin(306.4612)
Layer:addChild(btn_send_verify)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

