--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_delete
local Image_delete = ccui.ImageView:create()
Image_delete:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Image_delete:loadTexture("cp_session_btn_delete.png",1)
Image_delete:setScale9Enabled(true)
Image_delete:setCapInsets({x = 86, y = 56, width = 90, height = 58})
Image_delete:setTouchEnabled(true);
Image_delete:setLayoutComponentEnabled(true)
Image_delete:setName("Image_delete")
Image_delete:setTag(109)
Image_delete:setCascadeColorEnabled(true)
Image_delete:setCascadeOpacityEnabled(true)
Image_delete:setPosition(369.1200, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_delete)
layout:setSize({width = 262.0000, height = 165.0000})
layout:setLeftMargin(238.1200)
layout:setRightMargin(-500.1200)
layout:setTopMargin(-82.5000)
layout:setBottomMargin(-82.5000)
Node:addChild(Image_delete)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Image_bg:loadTexture("cp_frind_bg.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(220)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 1000.0000, height = 168.0000})
layout:setLeftMargin(-500.0000)
layout:setRightMargin(-500.0000)
layout:setTopMargin(-84.0000)
layout:setBottomMargin(-84.0000)
Node:addChild(Image_bg)

--Create Image_dot_bg
local Image_dot_bg = ccui.ImageView:create()
Image_dot_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Image_dot_bg:loadTexture("cp_friend_online_bg.png",1)
Image_dot_bg:setLayoutComponentEnabled(true)
Image_dot_bg:setName("Image_dot_bg")
Image_dot_bg:setTag(752)
Image_dot_bg:setCascadeColorEnabled(true)
Image_dot_bg:setCascadeOpacityEnabled(true)
Image_dot_bg:setPosition(56.9904, 84.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_dot_bg)
layout:setPositionPercentX(0.0570)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0570)
layout:setPercentHeight(0.3393)
layout:setSize({width = 57.0000, height = 57.0000})
layout:setLeftMargin(28.4904)
layout:setRightMargin(914.5096)
layout:setTopMargin(55.5000)
layout:setBottomMargin(55.5000)
Image_bg:addChild(Image_dot_bg)

--Create Image_dot
local Image_dot = ccui.ImageView:create()
Image_dot:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Image_dot:loadTexture("cp_friend_online_tag.png",1)
Image_dot:setLayoutComponentEnabled(true)
Image_dot:setName("Image_dot")
Image_dot:setTag(46)
Image_dot:setCascadeColorEnabled(true)
Image_dot:setCascadeOpacityEnabled(true)
Image_dot:setVisible(false)
Image_dot:setPosition(28.5000, 28.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_dot)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 57.0000, height = 57.0000})
Image_dot_bg:addChild(Image_dot)

--Create Image_head
local Image_head = ccui.ImageView:create()
Image_head:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Image_head:loadTexture("cp_friend_head_bg.png",1)
Image_head:setLayoutComponentEnabled(true)
Image_head:setName("Image_head")
Image_head:setTag(753)
Image_head:setCascadeColorEnabled(true)
Image_head:setCascadeOpacityEnabled(true)
Image_head:setPosition(169.4148, 86.3800)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_head)
layout:setPositionPercentX(0.1694)
layout:setPositionPercentY(0.5142)
layout:setPercentWidth(0.1200)
layout:setPercentHeight(0.7143)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(109.4148)
layout:setRightMargin(770.5852)
layout:setTopMargin(21.6200)
layout:setBottomMargin(26.3800)
Image_bg:addChild(Image_head)

--Create Image_gold
local Image_gold = ccui.ImageView:create()
Image_gold:ignoreContentAdaptWithSize(false)
Image_gold:loadTexture("common/common_gold.png",0)
Image_gold:setLayoutComponentEnabled(true)
Image_gold:setName("Image_gold")
Image_gold:setTag(47)
Image_gold:setCascadeColorEnabled(true)
Image_gold:setCascadeOpacityEnabled(true)
Image_gold:setPosition(341.9420, 55.6341)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_gold)
layout:setPositionPercentX(0.3419)
layout:setPositionPercentY(0.3312)
layout:setPercentWidth(0.0840)
layout:setPercentHeight(0.5000)
layout:setSize({width = 84.0000, height = 84.0000})
layout:setLeftMargin(299.9420)
layout:setRightMargin(616.0580)
layout:setTopMargin(70.3659)
layout:setBottomMargin(13.6341)
Image_bg:addChild(Image_gold)

--Create Text_gold
local Text_gold = ccui.Text:create()
Text_gold:ignoreContentAdaptWithSize(true)
Text_gold:setTextAreaSize({width = 0, height = 0})
Text_gold:setFontName("FZZhengHeiS-B-GB.ttf")
Text_gold:setFontSize(20)
Text_gold:setString([[0]])
Text_gold:setLayoutComponentEnabled(true)
Text_gold:setName("Text_gold")
Text_gold:setTag(48)
Text_gold:setCascadeColorEnabled(true)
Text_gold:setCascadeOpacityEnabled(true)
Text_gold:setAnchorPoint(0.0000, 0.5000)
Text_gold:setPosition(387.0019, 56.0263)
Text_gold:setTextColor({r = 57, g = 57, b = 57})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_gold)
layout:setPositionPercentX(0.3870)
layout:setPositionPercentY(0.3335)
layout:setPercentWidth(0.0170)
layout:setPercentHeight(0.1429)
layout:setSize({width = 17.0000, height = 24.0000})
layout:setLeftMargin(387.0019)
layout:setRightMargin(595.9981)
layout:setTopMargin(99.9737)
layout:setBottomMargin(44.0263)
Image_bg:addChild(Text_gold)

--Create Image_diamond
local Image_diamond = ccui.ImageView:create()
Image_diamond:ignoreContentAdaptWithSize(false)
Image_diamond:loadTexture("common/common_diamond.png",0)
Image_diamond:setLayoutComponentEnabled(true)
Image_diamond:setName("Image_diamond")
Image_diamond:setTag(49)
Image_diamond:setCascadeColorEnabled(true)
Image_diamond:setCascadeOpacityEnabled(true)
Image_diamond:setPosition(546.1468, 56.3048)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_diamond)
layout:setPositionPercentX(0.5461)
layout:setPositionPercentY(0.3351)
layout:setPercentWidth(0.0630)
layout:setPercentHeight(0.3750)
layout:setSize({width = 63.0000, height = 63.0000})
layout:setLeftMargin(514.6468)
layout:setRightMargin(422.3532)
layout:setTopMargin(80.1952)
layout:setBottomMargin(24.8048)
Image_bg:addChild(Image_diamond)

--Create Text_diamond
local Text_diamond = ccui.Text:create()
Text_diamond:ignoreContentAdaptWithSize(true)
Text_diamond:setTextAreaSize({width = 0, height = 0})
Text_diamond:setFontName("FZZhengHeiS-B-GB.ttf")
Text_diamond:setFontSize(20)
Text_diamond:setString([[0]])
Text_diamond:setLayoutComponentEnabled(true)
Text_diamond:setName("Text_diamond")
Text_diamond:setTag(50)
Text_diamond:setCascadeColorEnabled(true)
Text_diamond:setCascadeOpacityEnabled(true)
Text_diamond:setAnchorPoint(0.0000, 0.5000)
Text_diamond:setPosition(591.2055, 56.6970)
Text_diamond:setTextColor({r = 57, g = 57, b = 57})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_diamond)
layout:setPositionPercentX(0.5912)
layout:setPositionPercentY(0.3375)
layout:setPercentWidth(0.0170)
layout:setPercentHeight(0.1429)
layout:setSize({width = 17.0000, height = 24.0000})
layout:setLeftMargin(591.2055)
layout:setRightMargin(391.7945)
layout:setTopMargin(99.3030)
layout:setBottomMargin(44.6970)
Image_bg:addChild(Text_diamond)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("")
Text_name:setFontSize(42)
Text_name:setString([[UserName]])
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(232)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(0.0000, 0.5000)
Text_name:setPosition(314.4536, 128.4086)
Text_name:setTextColor({r = 38, g = 47, b = 42})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.3145)
layout:setPositionPercentY(0.7643)
layout:setPercentWidth(0.1680)
layout:setPercentHeight(0.2500)
layout:setSize({width = 168.0000, height = 42.0000})
layout:setLeftMargin(314.4536)
layout:setRightMargin(517.5464)
layout:setTopMargin(18.5914)
layout:setBottomMargin(107.4086)
Image_bg:addChild(Text_name)

--Create Panel_chat
local Panel_chat = ccui.Layout:create()
Panel_chat:ignoreContentAdaptWithSize(false)
Panel_chat:setClippingEnabled(true)
Panel_chat:setBackGroundColorOpacity(102)
Panel_chat:setTouchEnabled(true);
Panel_chat:setLayoutComponentEnabled(true)
Panel_chat:setName("Panel_chat")
Panel_chat:setTag(96)
Panel_chat:setCascadeColorEnabled(true)
Panel_chat:setCascadeOpacityEnabled(true)
Panel_chat:setPosition(851.8171, 7.4517)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_chat)
layout:setPositionPercentX(0.8518)
layout:setPositionPercentY(0.0444)
layout:setPercentWidth(0.1500)
layout:setPercentHeight(0.9524)
layout:setSize({width = 150.0000, height = 160.0000})
layout:setLeftMargin(851.8171)
layout:setRightMargin(-1.8171)
layout:setTopMargin(0.5483)
layout:setBottomMargin(7.4517)
Image_bg:addChild(Panel_chat)

--Create Button_chat
local Button_chat = ccui.Button:create()
Button_chat:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Button_chat:loadTextureNormal("cp_friend_tag_chat.png",1)
Button_chat:setTitleFontName("FZZhengHeiS-B-GB.ttf")
Button_chat:setTitleFontSize(42)
Button_chat:setTitleColor({r = 137, g = 30, b = 15})
Button_chat:setScale9Enabled(true)
Button_chat:setCapInsets({x = 15, y = 11, width = 53, height = 54})
Button_chat:setLayoutComponentEnabled(true)
Button_chat:setName("Button_chat")
Button_chat:setTag(754)
Button_chat:setCascadeColorEnabled(true)
Button_chat:setCascadeOpacityEnabled(true)
Button_chat:setPosition(75.0000, 80.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_chat)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5533)
layout:setPercentHeight(0.4750)
layout:setSize({width = 83.0000, height = 76.0000})
layout:setLeftMargin(33.5000)
layout:setRightMargin(33.5000)
layout:setTopMargin(42.0000)
layout:setBottomMargin(42.0000)
Panel_chat:addChild(Button_chat)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

