--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_bg:loadTexture("setting_bg.png",1)
Image_bg:setScale9Enabled(true)
Image_bg:setCapInsets({x = 343, y = 353, width = 354, height = 364})
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(87)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(1400.3560, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.7294)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5417)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1040.0000, height = 1080.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(880.3558)
layout:setRightMargin(-0.3558)
layout:setStretchHeightEnabled(true)
Layer:addChild(Image_bg)

--Create Image_header
local Image_header = ccui.ImageView:create()
Image_header:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_header:loadTexture("setting_top.png",1)
Image_header:setLayoutComponentEnabled(true)
Image_header:setName("Image_header")
Image_header:setTag(89)
Image_header:setCascadeColorEnabled(true)
Image_header:setCascadeOpacityEnabled(true)
Image_header:setPosition(519.4300, 1009.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_header)
layout:setPositionPercentX(0.4995)
layout:setPositionPercentY(0.9343)
layout:setPercentWidth(1.0144)
layout:setPercentHeight(0.1315)
layout:setSize({width = 1055.0000, height = 142.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(-8.0700)
layout:setRightMargin(-6.9299)
layout:setBottomMargin(938.0000)
Image_bg:addChild(Image_header)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontSize(48)
Text_title:setString([[------]])
Text_title:setTextHorizontalAlignment(1)
Text_title:setTextVerticalAlignment(1)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(181)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(527.5000, 75.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5282)
layout:setPercentWidth(0.1365)
layout:setPercentHeight(0.3380)
layout:setSize({width = 144.0000, height = 48.0000})
layout:setLeftMargin(455.5000)
layout:setRightMargin(455.5000)
layout:setTopMargin(43.0000)
layout:setBottomMargin(51.0000)
Image_header:addChild(Text_title)

--Create Image_content
local Image_content = ccui.ImageView:create()
Image_content:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_content:loadTexture("setting_mask_bg.png",1)
Image_content:setScale9Enabled(true)
Image_content:setCapInsets({x = 45, y = 45, width = 12, height = 12})
Image_content:setTouchEnabled(true);
Image_content:setLayoutComponentEnabled(true)
Image_content:setName("Image_content")
Image_content:setTag(88)
Image_content:setCascadeColorEnabled(true)
Image_content:setCascadeOpacityEnabled(true)
Image_content:setPosition(518.9534, 476.1407)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_content)
layout:setPositionPercentX(0.4990)
layout:setPositionPercentY(0.4409)
layout:setPercentWidth(0.9740)
layout:setPercentHeight(0.8233)
layout:setSize({width = 1013.0000, height = 889.1599})
layout:setVerticalEdge(3)
layout:setLeftMargin(12.4534)
layout:setRightMargin(14.5466)
layout:setTopMargin(159.2794)
layout:setBottomMargin(31.5607)
layout:setStretchHeightEnabled(true)
Image_bg:addChild(Image_content)

--Create Image_send
local Image_send = ccui.ImageView:create()
Image_send:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Image_send:loadTexture("cp_chat_input_bg.png",1)
Image_send:setLayoutComponentEnabled(true)
Image_send:setName("Image_send")
Image_send:setTag(186)
Image_send:setCascadeColorEnabled(true)
Image_send:setCascadeOpacityEnabled(true)
Image_send:setPosition(522.1831, 129.7340)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_send)
layout:setPositionPercentX(0.5021)
layout:setPositionPercentY(0.1201)
layout:setPercentWidth(0.9490)
layout:setPercentHeight(0.1676)
layout:setSize({width = 987.0000, height = 181.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(28.6831)
layout:setRightMargin(24.3169)
layout:setTopMargin(859.7660)
layout:setBottomMargin(39.2340)
Image_bg:addChild(Image_send)

--Create Button_voice
local Button_voice = ccui.Button:create()
Button_voice:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Button_voice:loadTextureNormal("cp_chat_btn_voice.png",1)
Button_voice:setTitleFontName("FZZhengHeiS-B-GB.ttf")
Button_voice:setTitleFontSize(36)
Button_voice:setTitleColor({r = 165, g = 42, b = 42})
Button_voice:setScale9Enabled(true)
Button_voice:setCapInsets({x = 15, y = 11, width = 90, height = 98})
Button_voice:setLayoutComponentEnabled(true)
Button_voice:setName("Button_voice")
Button_voice:setTag(83)
Button_voice:setCascadeColorEnabled(true)
Button_voice:setCascadeOpacityEnabled(true)
Button_voice:setPosition(89.6696, 87.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_voice)
layout:setPositionPercentX(0.0909)
layout:setPositionPercentY(0.4807)
layout:setPercentWidth(0.1216)
layout:setPercentHeight(0.6630)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(29.6696)
layout:setRightMargin(837.3304)
layout:setTopMargin(34.0000)
layout:setBottomMargin(27.0000)
Image_send:addChild(Button_voice)

--Create TextField_send
local TextField_send = ccui.TextField:create()
TextField_send:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_send:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_send:setFontName("")
TextField_send:setFontSize(36)
TextField_send:setPlaceHolder("该说点什么好呢？...")
TextField_send:setString([[]])
TextField_send:setMaxLengthEnabled(true)
TextField_send:setMaxLength(20)
TextField_send:setLayoutComponentEnabled(true)
TextField_send:setName("TextField_send")
TextField_send:setTag(187)
TextField_send:setCascadeColorEnabled(true)
TextField_send:setCascadeOpacityEnabled(true)
TextField_send:setAnchorPoint(0.0000, 0.5000)
TextField_send:setPosition(164.7681, 89.3538)
TextField_send:setColor({r = 78, g = 67, b = 39})
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_send)
layout:setPositionPercentX(0.1669)
layout:setPositionPercentY(0.4937)
layout:setPercentWidth(0.5775)
layout:setPercentHeight(0.2762)
layout:setSize({width = 570.0000, height = 50.0000})
layout:setLeftMargin(164.7681)
layout:setRightMargin(252.2319)
layout:setTopMargin(66.6462)
layout:setBottomMargin(64.3538)
Image_send:addChild(TextField_send)

--Create Button_send
local Button_send = ccui.Button:create()
Button_send:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/cardpartner/cardpartner_plist.plist")
Button_send:loadTextureNormal("cp_chat_btn_send.png",1)
Button_send:setTitleFontName("FZZhengHeiS-B-GB.ttf")
Button_send:setTitleFontSize(36)
Button_send:setTitleColor({r = 165, g = 42, b = 42})
Button_send:setScale9Enabled(true)
Button_send:setCapInsets({x = 15, y = 11, width = 153, height = 74})
Button_send:setLayoutComponentEnabled(true)
Button_send:setName("Button_send")
Button_send:setTag(188)
Button_send:setCascadeColorEnabled(true)
Button_send:setCascadeOpacityEnabled(true)
Button_send:setPosition(878.1094, 87.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_send)
layout:setPositionPercentX(0.8897)
layout:setPositionPercentY(0.4807)
layout:setPercentWidth(0.1854)
layout:setPercentHeight(0.5304)
layout:setSize({width = 183.0000, height = 96.0000})
layout:setLeftMargin(786.6094)
layout:setRightMargin(17.3906)
layout:setTopMargin(46.0000)
layout:setBottomMargin(39.0000)
Image_send:addChild(Button_send)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

