--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_prize
local Image_prize = ccui.ImageView:create()
Image_prize:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent2.plist")
Image_prize:loadTexture("hall_room_prize_bg.png",1)
Image_prize:setTouchEnabled(true);
Image_prize:setLayoutComponentEnabled(true)
Image_prize:setName("Image_prize")
Image_prize:setTag(18)
Image_prize:setCascadeColorEnabled(true)
Image_prize:setCascadeOpacityEnabled(true)
Image_prize:setPosition(1.0700, 32.2100)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_prize)
layout:setSize({width = 432.0000, height = 173.0000})
layout:setLeftMargin(-214.9300)
layout:setRightMargin(-217.0700)
layout:setTopMargin(-118.7100)
layout:setBottomMargin(-54.2900)
Node:addChild(Image_prize)

--Create hall_room_icon
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent2.plist")
local hall_room_icon = cc.Sprite:createWithSpriteFrameName("hall_room_prize_title.png")
hall_room_icon:setName("hall_room_icon")
hall_room_icon:setTag(54)
hall_room_icon:setCascadeColorEnabled(true)
hall_room_icon:setCascadeOpacityEnabled(true)
hall_room_icon:setPosition(266.0194, 90.6710)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_icon)
layout:setPositionPercentX(0.6158)
layout:setPositionPercentY(0.5241)
layout:setPercentWidth(0.4583)
layout:setPercentHeight(0.4046)
layout:setSize({width = 198.0000, height = 70.0000})
layout:setLeftMargin(167.0194)
layout:setRightMargin(66.9806)
layout:setTopMargin(47.3290)
layout:setBottomMargin(55.6710)
hall_room_icon:setBlendFunc({src = 1, dst = 771})
Image_prize:addChild(hall_room_icon)

--Create hall_room_trophy
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent2.plist")
local hall_room_trophy = cc.Sprite:createWithSpriteFrameName("hall_room_prize_trophy.png")
hall_room_trophy:setName("hall_room_trophy")
hall_room_trophy:setTag(89)
hall_room_trophy:setCascadeColorEnabled(true)
hall_room_trophy:setCascadeOpacityEnabled(true)
hall_room_trophy:setPosition(101.8778, 108.0397)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_trophy)
layout:setPositionPercentX(0.2358)
layout:setPositionPercentY(0.6245)
layout:setPercentWidth(0.5324)
layout:setPercentHeight(1.0636)
layout:setSize({width = 230.0000, height = 184.0000})
layout:setLeftMargin(-13.1222)
layout:setRightMargin(215.1222)
layout:setTopMargin(-27.0397)
layout:setBottomMargin(16.0397)
hall_room_trophy:setBlendFunc({src = 1, dst = 771})
Image_prize:addChild(hall_room_trophy)

--Create hall_room_cloud
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent2.plist")
local hall_room_cloud = cc.Sprite:createWithSpriteFrameName("hall_room_cloud.png")
hall_room_cloud:setName("hall_room_cloud")
hall_room_cloud:setTag(90)
hall_room_cloud:setCascadeColorEnabled(true)
hall_room_cloud:setCascadeOpacityEnabled(true)
hall_room_cloud:setPosition(372.9084, 60.3941)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_cloud)
layout:setPositionPercentX(0.8632)
layout:setPositionPercentY(0.3491)
layout:setPercentWidth(0.3727)
layout:setPercentHeight(0.4046)
layout:setSize({width = 161.0000, height = 70.0000})
layout:setLeftMargin(292.4084)
layout:setRightMargin(-21.4084)
layout:setTopMargin(77.6059)
layout:setBottomMargin(25.3941)
hall_room_cloud:setBlendFunc({src = 1, dst = 771})
Image_prize:addChild(hall_room_cloud)

--Create Image_count
local Image_count = ccui.ImageView:create()
Image_count:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent.plist")
Image_count:loadTexture("hall_room_label.png",1)
Image_count:setLayoutComponentEnabled(true)
Image_count:setName("Image_count")
Image_count:setTag(53)
Image_count:setCascadeColorEnabled(true)
Image_count:setCascadeOpacityEnabled(true)
Image_count:setPosition(0.1381, -92.0734)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_count)
layout:setSize({width = 231.0000, height = 47.0000})
layout:setLeftMargin(-115.3619)
layout:setRightMargin(-115.6381)
layout:setTopMargin(68.5734)
layout:setBottomMargin(-115.5734)
Node:addChild(Image_count)

--Create Text_count
local Text_count = ccui.Text:create()
Text_count:ignoreContentAdaptWithSize(true)
Text_count:setTextAreaSize({width = 0, height = 0})
Text_count:setFontName("FZZhengHeiS-B-GB.ttf")
Text_count:setFontSize(32)
Text_count:setString([[0人]])
Text_count:setLayoutComponentEnabled(true)
Text_count:setName("Text_count")
Text_count:setTag(52)
Text_count:setCascadeColorEnabled(true)
Text_count:setCascadeOpacityEnabled(true)
Text_count:setPosition(119.5536, 20.9525)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_count)
layout:setPositionPercentX(0.5175)
layout:setPositionPercentY(0.4458)
layout:setPercentWidth(0.2468)
layout:setPercentHeight(0.8298)
layout:setSize({width = 57.0000, height = 39.0000})
layout:setLeftMargin(91.0536)
layout:setRightMargin(82.9464)
layout:setTopMargin(6.5475)
layout:setBottomMargin(1.4525)
Image_count:addChild(Text_count)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/animation/hall_plist2.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("title_shade_prize.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(124)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(53.3133, 34.1998)
Sprite_1:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setSize({width = 222.0000, height = 94.0000})
layout:setLeftMargin(-57.6867)
layout:setRightMargin(-164.3133)
layout:setTopMargin(-81.1998)
layout:setBottomMargin(-12.8002)
Sprite_1:setBlendFunc({src = 1, dst = 1})
Node:addChild(Sprite_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(70)
result['animation']:setTimeSpeed(0.4167)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(53.3133)
localFrame:setY(34.1998)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(53.3133)
localFrame:setY(34.1998)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(53.3133)
localFrame:setY(34.1998)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(53.3133)
localFrame:setY(34.1998)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Sprite_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Sprite_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Sprite_1)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(Sprite_1)
--Create Animation List
local animation0 = {name="animation0", startIndex=1, endIndex=70}
result['animation']:addAnimationInfo(animation0)

result['root'] = Node
return result;
end

return Result

