--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create hall_room_high_bg
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent.plist")
local hall_room_high_bg = cc.Sprite:createWithSpriteFrameName("hall_room_high_bg.png")
hall_room_high_bg:setName("hall_room_high_bg")
hall_room_high_bg:setTag(68)
hall_room_high_bg:setCascadeColorEnabled(true)
hall_room_high_bg:setCascadeOpacityEnabled(true)
hall_room_high_bg:setPosition(0.0000, 0.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_high_bg)
layout:setSize({width = 376.0000, height = 377.0000})
layout:setLeftMargin(-188.0000)
layout:setRightMargin(-188.0000)
layout:setTopMargin(-188.5001)
layout:setBottomMargin(-188.4999)
hall_room_high_bg:setBlendFunc({src = 1, dst = 771})
Node:addChild(hall_room_high_bg)

--Create Button_high
local Button_high = ccui.Button:create()
Button_high:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent.plist")
Button_high:loadTextureNormal("hall_room_high_lady.png",1)
Button_high:setTitleFontSize(14)
Button_high:setTitleColor({r = 65, g = 65, b = 70})
Button_high:setScale9Enabled(true)
Button_high:setCapInsets({x = 15, y = 11, width = 515, height = 457})
Button_high:setLayoutComponentEnabled(true)
Button_high:setName("Button_high")
Button_high:setTag(67)
Button_high:setCascadeColorEnabled(true)
Button_high:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_high)
layout:setSize({width = 545.0000, height = 479.0000})
layout:setLeftMargin(-272.5000)
layout:setRightMargin(-272.5000)
layout:setTopMargin(-239.5000)
layout:setBottomMargin(-239.5000)
Node:addChild(Button_high)

--Create hall_room_high_trophy
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent.plist")
local hall_room_high_trophy = cc.Sprite:createWithSpriteFrameName("hall_room_high_trophy.png")
hall_room_high_trophy:setName("hall_room_high_trophy")
hall_room_high_trophy:setTag(74)
hall_room_high_trophy:setCascadeColorEnabled(true)
hall_room_high_trophy:setCascadeOpacityEnabled(true)
hall_room_high_trophy:setPosition(153.6205, -108.2349)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_high_trophy)
layout:setSize({width = 301.0000, height = 231.0000})
layout:setLeftMargin(3.1205)
layout:setRightMargin(-304.1205)
layout:setTopMargin(-7.2651)
layout:setBottomMargin(-223.7349)
hall_room_high_trophy:setBlendFunc({src = 1, dst = 771})
Node:addChild(hall_room_high_trophy)

--Create hall_room_high_titlebg
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent.plist")
local hall_room_high_titlebg = cc.Sprite:createWithSpriteFrameName("hall_room_high_titlebg.png")
hall_room_high_titlebg:setName("hall_room_high_titlebg")
hall_room_high_titlebg:setTag(73)
hall_room_high_titlebg:setCascadeColorEnabled(true)
hall_room_high_titlebg:setCascadeOpacityEnabled(true)
hall_room_high_titlebg:setPosition(0.0002, -186.8290)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_high_titlebg)
layout:setSize({width = 545.0000, height = 111.0000})
layout:setLeftMargin(-272.4998)
layout:setRightMargin(-272.5002)
layout:setTopMargin(131.3290)
layout:setBottomMargin(-242.3290)
hall_room_high_titlebg:setBlendFunc({src = 1, dst = 771})
Node:addChild(hall_room_high_titlebg)

--Create hall_room_high_titlebg1
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent.plist")
local hall_room_high_titlebg1 = cc.Sprite:createWithSpriteFrameName("hall_room_high_titlebg.png")
hall_room_high_titlebg1:setName("hall_room_high_titlebg1")
hall_room_high_titlebg1:setTag(24)
hall_room_high_titlebg1:setCascadeColorEnabled(true)
hall_room_high_titlebg1:setCascadeOpacityEnabled(true)
hall_room_high_titlebg1:setPosition(0.0000, -186.8300)
hall_room_high_titlebg1:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_high_titlebg1)
layout:setSize({width = 545.0000, height = 111.0000})
layout:setLeftMargin(-272.5000)
layout:setRightMargin(-272.5000)
layout:setTopMargin(131.3300)
layout:setBottomMargin(-242.3300)
hall_room_high_titlebg1:setBlendFunc({src = 1, dst = 1})
Node:addChild(hall_room_high_titlebg1)

--Create hall_room_high_title
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/plist/hallcontent.plist")
local hall_room_high_title = cc.Sprite:createWithSpriteFrameName("hall_room_high_title.png")
hall_room_high_title:setName("hall_room_high_title")
hall_room_high_title:setTag(72)
hall_room_high_title:setCascadeColorEnabled(true)
hall_room_high_title:setCascadeOpacityEnabled(true)
hall_room_high_title:setPosition(0.0002, -165.3946)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_high_title)
layout:setSize({width = 284.0000, height = 97.0000})
layout:setLeftMargin(-141.9998)
layout:setRightMargin(-142.0002)
layout:setTopMargin(116.8946)
layout:setBottomMargin(-213.8946)
hall_room_high_title:setBlendFunc({src = 1, dst = 771})
Node:addChild(hall_room_high_title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

