--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1020.0000, height = 809.0000})

--Create Image_top
local Image_top = ccui.ImageView:create()
Image_top:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/userinfo/userinfo_plist.plist")
Image_top:loadTexture("userinfo_img_nickname_bg.png",1)
Image_top:setLayoutComponentEnabled(true)
Image_top:setName("Image_top")
Image_top:setTag(188)
Image_top:setCascadeColorEnabled(true)
Image_top:setCascadeOpacityEnabled(true)
Image_top:setPosition(512.1625, 612.0187)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_top)
layout:setPositionPercentX(0.5021)
layout:setPositionPercentY(0.7565)
layout:setPercentWidth(0.9755)
layout:setPercentHeight(0.4574)
layout:setSize({width = 995.0000, height = 370.0000})
layout:setLeftMargin(14.6625)
layout:setRightMargin(10.3375)
layout:setTopMargin(11.9813)
layout:setBottomMargin(427.0187)
Layer:addChild(Image_top)

--Create TextField_name
local TextField_name = ccui.TextField:create()
TextField_name:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_name:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_name:setFontName("")
TextField_name:setFontSize(36)
TextField_name:setPlaceHolder("")
TextField_name:setString([[]])
TextField_name:setMaxLengthEnabled(true)
TextField_name:setMaxLength(14)
TextField_name:setLayoutComponentEnabled(true)
TextField_name:setName("TextField_name")
TextField_name:setTag(557)
TextField_name:setCascadeColorEnabled(true)
TextField_name:setCascadeOpacityEnabled(true)
TextField_name:setAnchorPoint(0.0000, 0.5000)
TextField_name:setPosition(93.7216, 272.5700)
TextField_name:setColor({r = 153, g = 154, b = 154})
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_name)
layout:setPositionPercentX(0.0942)
layout:setPositionPercentY(0.7367)
layout:setPercentWidth(0.7538)
layout:setPercentHeight(0.1081)
layout:setSize({width = 750.0000, height = 40.0000})
layout:setLeftMargin(93.7216)
layout:setRightMargin(151.2784)
layout:setTopMargin(77.4300)
layout:setBottomMargin(252.5700)
Image_top:addChild(TextField_name)

--Create Button_clear
local Button_clear = ccui.Button:create()
Button_clear:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/userinfo/userinfo_plist.plist")
Button_clear:loadTextureNormal("userinfo_img_clear.png",1)
Button_clear:setTitleFontSize(14)
Button_clear:setTitleColor({r = 65, g = 65, b = 70})
Button_clear:setScale9Enabled(true)
Button_clear:setCapInsets({x = 15, y = 11, width = 12, height = 20})
Button_clear:setLayoutComponentEnabled(true)
Button_clear:setName("Button_clear")
Button_clear:setTag(558)
Button_clear:setCascadeColorEnabled(true)
Button_clear:setCascadeOpacityEnabled(true)
Button_clear:setPosition(877.4052, 272.4849)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_clear)
layout:setPositionPercentX(0.8818)
layout:setPositionPercentY(0.7364)
layout:setPercentWidth(0.0422)
layout:setPercentHeight(0.1135)
layout:setSize({width = 42.0000, height = 42.0000})
layout:setLeftMargin(856.4052)
layout:setRightMargin(96.5948)
layout:setTopMargin(76.5151)
layout:setBottomMargin(251.4849)
Image_top:addChild(Button_clear)

--Create Image_tip1
local Image_tip1 = ccui.ImageView:create()
Image_tip1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/userinfo/userinfo_plist.plist")
Image_tip1:loadTexture("userinfo_img_icon1.png",1)
Image_tip1:setLayoutComponentEnabled(true)
Image_tip1:setName("Image_tip1")
Image_tip1:setTag(559)
Image_tip1:setCascadeColorEnabled(true)
Image_tip1:setCascadeOpacityEnabled(true)
Image_tip1:setPosition(89.8841, 137.9160)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tip1)
layout:setPositionPercentX(0.0903)
layout:setPositionPercentY(0.3727)
layout:setPercentWidth(0.0261)
layout:setPercentHeight(0.0811)
layout:setSize({width = 26.0000, height = 30.0000})
layout:setLeftMargin(76.8841)
layout:setRightMargin(892.1159)
layout:setTopMargin(217.0840)
layout:setBottomMargin(122.9160)
Image_top:addChild(Image_tip1)

--Create Text_tip1
local Text_tip1 = ccui.Text:create()
Text_tip1:ignoreContentAdaptWithSize(true)
Text_tip1:setTextAreaSize({width = 0, height = 0})
Text_tip1:setFontName("FZZhengHeiS-B-GB.ttf")
Text_tip1:setFontSize(32)
Text_tip1:setString([[使用昵称可以让好友更容易认出你。]])
Text_tip1:setLayoutComponentEnabled(true)
Text_tip1:setName("Text_tip1")
Text_tip1:setTag(561)
Text_tip1:setCascadeColorEnabled(true)
Text_tip1:setCascadeOpacityEnabled(true)
Text_tip1:setAnchorPoint(0.0000, 0.5000)
Text_tip1:setPosition(124.8319, 134.7186)
Text_tip1:setTextColor({r = 62, g = 50, b = 28})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_tip1)
layout:setPositionPercentX(0.1255)
layout:setPositionPercentY(0.3641)
layout:setPercentWidth(0.4995)
layout:setPercentHeight(0.1054)
layout:setSize({width = 497.0000, height = 39.0000})
layout:setLeftMargin(124.8319)
layout:setRightMargin(373.1681)
layout:setTopMargin(215.7814)
layout:setBottomMargin(115.2186)
Image_top:addChild(Text_tip1)

--Create Image_tip2
local Image_tip2 = ccui.ImageView:create()
Image_tip2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/userinfo/userinfo_plist.plist")
Image_tip2:loadTexture("userinfo_img_icon1.png",1)
Image_tip2:setLayoutComponentEnabled(true)
Image_tip2:setName("Image_tip2")
Image_tip2:setTag(560)
Image_tip2:setCascadeColorEnabled(true)
Image_tip2:setCascadeOpacityEnabled(true)
Image_tip2:setPosition(88.5023, 61.0714)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tip2)
layout:setPositionPercentX(0.0889)
layout:setPositionPercentY(0.1651)
layout:setPercentWidth(0.0261)
layout:setPercentHeight(0.0811)
layout:setSize({width = 26.0000, height = 30.0000})
layout:setLeftMargin(75.5023)
layout:setRightMargin(893.4977)
layout:setTopMargin(293.9286)
layout:setBottomMargin(46.0714)
Image_top:addChild(Image_tip2)

--Create Text_tip2
local Text_tip2 = ccui.Text:create()
Text_tip2:ignoreContentAdaptWithSize(true)
Text_tip2:setTextAreaSize({width = 0, height = 0})
Text_tip2:setFontName("FZZhengHeiS-B-GB.ttf")
Text_tip2:setFontSize(32)
Text_tip2:setString([[昵称最长不超过7个字。]])
Text_tip2:setLayoutComponentEnabled(true)
Text_tip2:setName("Text_tip2")
Text_tip2:setTag(562)
Text_tip2:setCascadeColorEnabled(true)
Text_tip2:setCascadeOpacityEnabled(true)
Text_tip2:setAnchorPoint(0.0000, 0.5000)
Text_tip2:setPosition(126.1289, 62.0383)
Text_tip2:setTextColor({r = 62, g = 50, b = 28})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_tip2)
layout:setPositionPercentX(0.1268)
layout:setPositionPercentY(0.1677)
layout:setPercentWidth(0.3286)
layout:setPercentHeight(0.1054)
layout:setSize({width = 327.0000, height = 39.0000})
layout:setLeftMargin(126.1289)
layout:setRightMargin(541.8711)
layout:setTopMargin(288.4617)
layout:setBottomMargin(42.5383)
Image_top:addChild(Text_tip2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

