--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/roomchat/roomchat_plist.plist")
Image_bg:loadTexture("roomchat_char_inputbg.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(209)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 987.0000, height = 181.0000})
layout:setLeftMargin(-493.5000)
layout:setRightMargin(-493.5000)
layout:setTopMargin(-90.5000)
layout:setBottomMargin(-90.5000)
Node:addChild(Image_bg)

--Create TextField_1
local TextField_1 = ccui.TextField:create()
TextField_1:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_1:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_1:setFontName("")
TextField_1:setFontSize(36)
TextField_1:setPlaceHolder("该说点什么好呢？...")
TextField_1:setString([[]])
TextField_1:setMaxLengthEnabled(true)
TextField_1:setMaxLength(20)
TextField_1:setLayoutComponentEnabled(true)
TextField_1:setName("TextField_1")
TextField_1:setTag(230)
TextField_1:setCascadeColorEnabled(true)
TextField_1:setCascadeOpacityEnabled(true)
TextField_1:setAnchorPoint(0.0000, 0.5000)
TextField_1:setPosition(45.4424, 96.1400)
TextField_1:setColor({r = 78, g = 67, b = 39})
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_1)
layout:setPositionPercentX(0.0460)
layout:setPositionPercentY(0.5312)
layout:setPercentWidth(0.5775)
layout:setPercentHeight(0.2431)
layout:setSize({width = 570.0000, height = 44.0000})
layout:setLeftMargin(45.4424)
layout:setRightMargin(371.5576)
layout:setTopMargin(62.8600)
layout:setBottomMargin(74.1400)
Image_bg:addChild(TextField_1)

--Create Button_send
local Button_send = ccui.Button:create()
Button_send:ignoreContentAdaptWithSize(false)
Button_send:loadTextureNormal("common/common_btn_yellow3.png",0)
Button_send:setTitleFontName("FZZhengHeiS-B-GB.ttf")
Button_send:setTitleFontSize(36)
Button_send:setTitleText("发送")
Button_send:setTitleColor({r = 165, g = 42, b = 42})
Button_send:setScale9Enabled(true)
Button_send:setCapInsets({x = 15, y = 11, width = 208, height = 78})
Button_send:setLayoutComponentEnabled(true)
Button_send:setName("Button_send")
Button_send:setTag(229)
Button_send:setCascadeColorEnabled(true)
Button_send:setCascadeOpacityEnabled(true)
Button_send:setPosition(814.6880, 96.1400)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_send)
layout:setPositionPercentX(0.8254)
layout:setPositionPercentY(0.5312)
layout:setPercentWidth(0.2411)
layout:setPercentHeight(0.5525)
layout:setSize({width = 238.0000, height = 100.0000})
layout:setLeftMargin(695.6880)
layout:setRightMargin(53.3120)
layout:setTopMargin(34.8600)
layout:setBottomMargin(46.1400)
Image_bg:addChild(Button_send)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

