--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create foldedmenu_bg
local foldedmenu_bg = ccui.ImageView:create()
foldedmenu_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("guandan/guandanMenu/guandan_foldedMenu.plist")
foldedmenu_bg:loadTexture("guandan_foldedMenu_bg.png",1)
foldedmenu_bg:setTouchEnabled(true);
foldedmenu_bg:setLayoutComponentEnabled(true)
foldedmenu_bg:setName("foldedmenu_bg")
foldedmenu_bg:setTag(68)
foldedmenu_bg:setCascadeColorEnabled(true)
foldedmenu_bg:setCascadeOpacityEnabled(true)
foldedmenu_bg:setAnchorPoint(0.5000, 1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(foldedmenu_bg)
layout:setSize({width = 106.0000, height = 500.0000})
layout:setLeftMargin(-53.0000)
layout:setRightMargin(-53.0000)
layout:setBottomMargin(-500.0000)
Node:addChild(foldedmenu_bg)

--Create foldedmenu_set
local foldedmenu_set = ccui.Button:create()
foldedmenu_set:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("guandan/guandanMenu/guandan_foldedMenu.plist")
foldedmenu_set:loadTextureNormal("guandan_foldedMenu_set.png",1)
foldedmenu_set:setTitleFontSize(14)
foldedmenu_set:setTitleColor({r = 65, g = 65, b = 70})
foldedmenu_set:setScale9Enabled(true)
foldedmenu_set:setCapInsets({x = 15, y = 11, width = 76, height = 95})
foldedmenu_set:setLayoutComponentEnabled(true)
foldedmenu_set:setName("foldedmenu_set")
foldedmenu_set:setTag(71)
foldedmenu_set:setCascadeColorEnabled(true)
foldedmenu_set:setCascadeOpacityEnabled(true)
foldedmenu_set:setPosition(56.5286, 326.1427)
layout = ccui.LayoutComponent:bindLayoutComponent(foldedmenu_set)
layout:setPositionPercentX(0.5333)
layout:setPositionPercentY(0.6523)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2340)
layout:setSize({width = 106.0000, height = 117.0000})
layout:setLeftMargin(3.5286)
layout:setRightMargin(-3.5286)
layout:setTopMargin(115.3573)
layout:setBottomMargin(267.6427)
foldedmenu_bg:addChild(foldedmenu_set)

--Create foldedmenu_trusteeship
local foldedmenu_trusteeship = ccui.Button:create()
foldedmenu_trusteeship:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("guandan/guandanMenu/guandan_foldedMenu.plist")
foldedmenu_trusteeship:loadTextureNormal("guandan_foldedMenu_trusteeship .png",1)
foldedmenu_trusteeship:setTitleFontSize(14)
foldedmenu_trusteeship:setTitleColor({r = 65, g = 65, b = 70})
foldedmenu_trusteeship:setScale9Enabled(true)
foldedmenu_trusteeship:setCapInsets({x = 15, y = 11, width = 76, height = 95})
foldedmenu_trusteeship:setLayoutComponentEnabled(true)
foldedmenu_trusteeship:setName("foldedmenu_trusteeship")
foldedmenu_trusteeship:setTag(72)
foldedmenu_trusteeship:setCascadeColorEnabled(true)
foldedmenu_trusteeship:setCascadeOpacityEnabled(true)
foldedmenu_trusteeship:setPosition(56.5286, 202.6512)
layout = ccui.LayoutComponent:bindLayoutComponent(foldedmenu_trusteeship)
layout:setPositionPercentX(0.5333)
layout:setPositionPercentY(0.4053)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2340)
layout:setSize({width = 106.0000, height = 117.0000})
layout:setLeftMargin(3.5286)
layout:setRightMargin(-3.5286)
layout:setTopMargin(238.8488)
layout:setBottomMargin(144.1512)
foldedmenu_bg:addChild(foldedmenu_trusteeship)

--Create foldedmenu_exit
local foldedmenu_exit = ccui.Button:create()
foldedmenu_exit:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("guandan/guandanMenu/guandan_foldedMenu.plist")
foldedmenu_exit:loadTextureNormal("guandan_foldedMenu_exit.png",1)
foldedmenu_exit:setTitleFontSize(14)
foldedmenu_exit:setTitleColor({r = 65, g = 65, b = 70})
foldedmenu_exit:setScale9Enabled(true)
foldedmenu_exit:setCapInsets({x = 15, y = 11, width = 76, height = 95})
foldedmenu_exit:setLayoutComponentEnabled(true)
foldedmenu_exit:setName("foldedmenu_exit")
foldedmenu_exit:setTag(73)
foldedmenu_exit:setCascadeColorEnabled(true)
foldedmenu_exit:setCascadeOpacityEnabled(true)
foldedmenu_exit:setPosition(56.5287, 73.7460)
layout = ccui.LayoutComponent:bindLayoutComponent(foldedmenu_exit)
layout:setPositionPercentX(0.5333)
layout:setPositionPercentY(0.1475)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2340)
layout:setSize({width = 106.0000, height = 117.0000})
layout:setLeftMargin(3.5287)
layout:setRightMargin(-3.5287)
layout:setTopMargin(367.7540)
layout:setBottomMargin(15.2460)
foldedmenu_bg:addChild(foldedmenu_exit)

--Create foldedmenu_main
local foldedmenu_main = ccui.Button:create()
foldedmenu_main:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("guandan/guandanMenu/guandan_foldedMenu.plist")
foldedmenu_main:loadTextureNormal("guandan_foldedMenu_main.png",1)
foldedmenu_main:setTitleFontSize(14)
foldedmenu_main:setTitleColor({r = 65, g = 65, b = 70})
foldedmenu_main:setScale9Enabled(true)
foldedmenu_main:setCapInsets({x = 15, y = 11, width = 76, height = 95})
foldedmenu_main:setLayoutComponentEnabled(true)
foldedmenu_main:setName("foldedmenu_main")
foldedmenu_main:setTag(70)
foldedmenu_main:setCascadeColorEnabled(true)
foldedmenu_main:setCascadeOpacityEnabled(true)
foldedmenu_main:setPosition(0.5387, -49.1662)
layout = ccui.LayoutComponent:bindLayoutComponent(foldedmenu_main)
layout:setSize({width = 106.0000, height = 117.0000})
layout:setLeftMargin(-52.4613)
layout:setRightMargin(-53.5387)
layout:setTopMargin(-9.3338)
layout:setBottomMargin(-107.6662)
Node:addChild(foldedmenu_main)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

