--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hotupdate/hotupdate_plist.plist")
Image_bg:loadTexture("hotud_progress_bg.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(24)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(0.0000, 257.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 995.0000, height = 514.0000})
layout:setLeftMargin(-497.5000)
layout:setRightMargin(-497.5000)
layout:setTopMargin(-514.0000)
Node:addChild(Image_bg)

--Create Image_4
local Image_4 = ccui.ImageView:create()
Image_4:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hotupdate/hotupdate_plist.plist")
Image_4:loadTexture("hotud_segline2.png",1)
Image_4:setLayoutComponentEnabled(true)
Image_4:setName("Image_4")
Image_4:setTag(28)
Image_4:setCascadeColorEnabled(true)
Image_4:setCascadeOpacityEnabled(true)
Image_4:setPosition(497.5000, 257.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1012)
layout:setSize({width = 995.0000, height = 52.0000})
layout:setTopMargin(231.0000)
layout:setBottomMargin(231.0000)
Image_bg:addChild(Image_4)

--Create Image_progress
local Image_progress = ccui.ImageView:create()
Image_progress:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hotupdate/hotupdate_plist.plist")
Image_progress:loadTexture("hotud_progress_bg2.png",1)
Image_progress:setLayoutComponentEnabled(true)
Image_progress:setName("Image_progress")
Image_progress:setTag(29)
Image_progress:setCascadeColorEnabled(true)
Image_progress:setCascadeOpacityEnabled(true)
Image_progress:setPosition(497.5000, 256.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_progress)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4633)
layout:setPercentHeight(0.8969)
layout:setSize({width = 461.0000, height = 461.0000})
layout:setLeftMargin(267.0000)
layout:setRightMargin(267.0000)
layout:setTopMargin(26.5001)
layout:setBottomMargin(26.4999)
Image_bg:addChild(Image_progress)

--Create Image_progressbg
local Image_progressbg = ccui.ImageView:create()
Image_progressbg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hotupdate/hotupdate_plist.plist")
Image_progressbg:loadTexture("hotud_progress_empty.png",1)
Image_progressbg:setLayoutComponentEnabled(true)
Image_progressbg:setName("Image_progressbg")
Image_progressbg:setTag(31)
Image_progressbg:setCascadeColorEnabled(true)
Image_progressbg:setCascadeOpacityEnabled(true)
Image_progressbg:setPosition(230.5000, 230.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_progressbg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9111)
layout:setPercentHeight(0.9111)
layout:setSize({width = 420.0000, height = 420.0000})
layout:setLeftMargin(20.5000)
layout:setRightMargin(20.5000)
layout:setTopMargin(20.5000)
layout:setBottomMargin(20.5000)
Image_progress:addChild(Image_progressbg)

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(29)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setPosition(395.2122, 158.8991)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(0.3972)
layout:setPositionPercentY(0.3091)
layout:setPercentWidth(0.2010)
layout:setPercentHeight(0.3891)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(395.2122)
layout:setRightMargin(399.7878)
layout:setTopMargin(155.1009)
layout:setBottomMargin(158.8991)
Image_bg:addChild(Panel_1)

--Create Text_percent
local Text_percent = ccui.Text:create()
Text_percent:ignoreContentAdaptWithSize(true)
Text_percent:setTextAreaSize({width = 0, height = 0})
Text_percent:setFontName("FZZhengHeiS-B-GB.ttf")
Text_percent:setFontSize(70)
Text_percent:setString([[0%]])
Text_percent:setLayoutComponentEnabled(true)
Text_percent:setName("Text_percent")
Text_percent:setTag(27)
Text_percent:setCascadeColorEnabled(true)
Text_percent:setCascadeOpacityEnabled(true)
Text_percent:setPosition(105.5472, 94.8590)
Text_percent:setTextColor({r = 255, g = 241, b = 10})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_percent)
layout:setPositionPercentX(0.5277)
layout:setPositionPercentY(0.4743)
layout:setPercentWidth(0.6300)
layout:setPercentHeight(0.4300)
layout:setSize({width = 126.0000, height = 86.0000})
layout:setLeftMargin(42.5472)
layout:setRightMargin(31.4528)
layout:setTopMargin(62.1410)
layout:setBottomMargin(51.8590)
Panel_1:addChild(Text_percent)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(false)
Panel_2:setBackGroundColorOpacity(102)
Panel_2:setTouchEnabled(true);
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(30)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setVisible(false)
Panel_2:setPosition(397.1960, 158.2514)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPositionPercentX(0.3992)
layout:setPositionPercentY(0.3079)
layout:setPercentWidth(0.2010)
layout:setPercentHeight(0.3891)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(397.1960)
layout:setRightMargin(397.8040)
layout:setTopMargin(155.7487)
layout:setBottomMargin(158.2514)
Image_bg:addChild(Panel_2)

--Create Text_fail
local Text_fail = ccui.Text:create()
Text_fail:ignoreContentAdaptWithSize(true)
Text_fail:setTextAreaSize({width = 0, height = 0})
Text_fail:setFontName("FZZhengHeiS-B-GB.ttf")
Text_fail:setFontSize(48)
Text_fail:setString([[下载失败]])
Text_fail:setLayoutComponentEnabled(true)
Text_fail:setName("Text_fail")
Text_fail:setTag(28)
Text_fail:setCascadeColorEnabled(true)
Text_fail:setCascadeOpacityEnabled(true)
Text_fail:setPosition(96.1912, 119.8616)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_fail)
layout:setPositionPercentX(0.4810)
layout:setPositionPercentY(0.5993)
layout:setPercentWidth(0.9650)
layout:setPercentHeight(0.2950)
layout:setSize({width = 193.0000, height = 59.0000})
layout:setLeftMargin(-0.3088)
layout:setRightMargin(7.3088)
layout:setTopMargin(50.6384)
layout:setBottomMargin(90.3616)
Panel_2:addChild(Text_fail)

--Create Text_redownload
local Text_redownload = ccui.Text:create()
Text_redownload:ignoreContentAdaptWithSize(true)
Text_redownload:setTextAreaSize({width = 0, height = 0})
Text_redownload:setFontName("FZZhengHeiS-B-GB.ttf")
Text_redownload:setFontSize(36)
Text_redownload:setString([[点击重新下载]])
Text_redownload:setTouchEnabled(true);
Text_redownload:setLayoutComponentEnabled(true)
Text_redownload:setName("Text_redownload")
Text_redownload:setTag(32)
Text_redownload:setCascadeColorEnabled(true)
Text_redownload:setCascadeOpacityEnabled(true)
Text_redownload:setPosition(99.5164, 63.0990)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_redownload)
layout:setPositionPercentX(0.4976)
layout:setPositionPercentY(0.3155)
layout:setPercentWidth(1.0850)
layout:setPercentHeight(0.2200)
layout:setSize({width = 217.0000, height = 44.0000})
layout:setLeftMargin(-8.9836)
layout:setRightMargin(-8.0164)
layout:setTopMargin(114.9010)
layout:setBottomMargin(41.0990)
Panel_2:addChild(Text_redownload)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

