--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hotupdate/hotupdate_plist.plist")
Image_bg:loadTexture("hotud_progress_bg.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(11)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(0.0000, 257.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 995.0000, height = 514.0000})
layout:setLeftMargin(-497.5000)
layout:setRightMargin(-497.5000)
layout:setTopMargin(-514.0000)
Node:addChild(Image_bg)

--Create Image_desc
local Image_desc = ccui.ImageView:create()
Image_desc:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hotupdate/hotupdate_plist.plist")
Image_desc:loadTexture("hotud_desc_bg2.png",1)
Image_desc:setLayoutComponentEnabled(true)
Image_desc:setName("Image_desc")
Image_desc:setTag(12)
Image_desc:setCascadeColorEnabled(true)
Image_desc:setCascadeOpacityEnabled(true)
Image_desc:setPosition(499.0939, 269.4374)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_desc)
layout:setPositionPercentX(0.5016)
layout:setPositionPercentY(0.5242)
layout:setPercentWidth(0.9045)
layout:setPercentHeight(0.8852)
layout:setSize({width = 900.0000, height = 455.0000})
layout:setLeftMargin(49.0939)
layout:setRightMargin(45.9061)
layout:setTopMargin(17.0626)
layout:setBottomMargin(41.9374)
Image_bg:addChild(Image_desc)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(false)
Text_1:setFontName("FZZhengHeiS-B-GB.ttf")
Text_1:setFontSize(30)
Text_1:setString([[为了更好的游戏体验，请您更新至最新版本，本次更新约0K，建议您在稳定的网络环境下进行更新。]])
Text_1:setTextVerticalAlignment(1)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(14)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setAnchorPoint(0.0000, 0.5000)
Text_1:setPosition(324.9452, 313.9042)
Text_1:setTextColor({r = 153, g = 154, b = 154})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.3611)
layout:setPositionPercentY(0.6899)
layout:setPercentWidth(0.6000)
layout:setPercentHeight(0.4396)
layout:setSize({width = 540.0000, height = 200.0000})
layout:setLeftMargin(324.9452)
layout:setRightMargin(35.0548)
layout:setTopMargin(41.0958)
layout:setBottomMargin(213.9042)
Image_desc:addChild(Text_1)

--Create Button_update
local Button_update = ccui.Button:create()
Button_update:ignoreContentAdaptWithSize(false)
Button_update:loadTextureNormal("common/common_btn_yellow.png",0)
Button_update:setTitleFontName("FZZhengHeiS-B-GB.ttf")
Button_update:setTitleFontSize(44)
Button_update:setTitleText("立即下载")
Button_update:setTitleColor({r = 143, g = 30, b = 63})
Button_update:setScale9Enabled(true)
Button_update:setCapInsets({x = 15, y = 11, width = 278, height = 91})
Button_update:setLayoutComponentEnabled(true)
Button_update:setName("Button_update")
Button_update:setTag(13)
Button_update:setCascadeColorEnabled(true)
Button_update:setCascadeOpacityEnabled(true)
Button_update:setPosition(673.6243, 112.8744)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_update)
layout:setPositionPercentX(0.6770)
layout:setPositionPercentY(0.2196)
layout:setPercentWidth(0.3095)
layout:setPercentHeight(0.2198)
layout:setSize({width = 308.0000, height = 113.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(519.6243)
layout:setRightMargin(167.3757)
layout:setTopMargin(344.6256)
layout:setBottomMargin(56.3744)
Image_bg:addChild(Button_update)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

