--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_bg:loadTexture("setting_bg.png",1)
Image_bg:setScale9Enabled(true)
Image_bg:setCapInsets({x = 343, y = 353, width = 354, height = 364})
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(26)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(1400.3560, 540.9486)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.7294)
layout:setPositionPercentY(0.5009)
layout:setPercentWidth(0.5417)
layout:setPercentHeight(0.9907)
layout:setSize({width = 1040.0000, height = 1070.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(880.3558)
layout:setRightMargin(-0.3558)
layout:setTopMargin(4.0514)
layout:setBottomMargin(5.9486)
layout:setStretchHeightEnabled(true)
Layer:addChild(Image_bg)

--Create Image_header
local Image_header = ccui.ImageView:create()
Image_header:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_header:loadTexture("setting_top.png",1)
Image_header:setLayoutComponentEnabled(true)
Image_header:setName("Image_header")
Image_header:setTag(27)
Image_header:setCascadeColorEnabled(true)
Image_header:setCascadeOpacityEnabled(true)
Image_header:setPosition(519.4295, 999.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_header)
layout:setPositionPercentX(0.4995)
layout:setPositionPercentY(0.9336)
layout:setPercentWidth(1.0144)
layout:setPercentHeight(0.1327)
layout:setSize({width = 1055.0000, height = 142.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(-8.0705)
layout:setRightMargin(-6.9294)
layout:setBottomMargin(928.0000)
Image_bg:addChild(Image_header)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("FZZhengHeiS-B-GB.ttf")
Text_title:setFontSize(56)
Text_title:setString([[游戏更新]])
Text_title:enableShadow({r = 68, g = 36, b = 53, a = 255}, {width = 2, height = -2}, 0)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(28)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(527.0000, 78.0308)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.4995)
layout:setPositionPercentY(0.5495)
layout:setPercentWidth(0.2133)
layout:setPercentHeight(0.4789)
layout:setSize({width = 225.0000, height = 68.0000})
layout:setLeftMargin(414.5000)
layout:setRightMargin(415.5000)
layout:setTopMargin(29.9692)
layout:setBottomMargin(44.0308)
Image_header:addChild(Text_title)

--Create Image_content
local Image_content = ccui.ImageView:create()
Image_content:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_content:loadTexture("setting_mask_bg.png",1)
Image_content:setScale9Enabled(true)
Image_content:setCapInsets({x = 45, y = 45, width = 12, height = 12})
Image_content:setTouchEnabled(true);
Image_content:setLayoutComponentEnabled(true)
Image_content:setName("Image_content")
Image_content:setTag(553)
Image_content:setCascadeColorEnabled(true)
Image_content:setCascadeOpacityEnabled(true)
Image_content:setPosition(518.9534, 472.0242)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_content)
layout:setPositionPercentX(0.4990)
layout:setPositionPercentY(0.4411)
layout:setPercentWidth(0.9740)
layout:setPercentHeight(0.8233)
layout:setSize({width = 1013.0000, height = 880.9310})
layout:setVerticalEdge(1)
layout:setLeftMargin(12.4534)
layout:setRightMargin(14.5466)
layout:setTopMargin(157.5103)
layout:setBottomMargin(31.5587)
layout:setStretchHeightEnabled(true)
Image_bg:addChild(Image_content)

--Create FileNode_1
innerCSD = require("csb.hall.hotupdate.Node_UpdateDesc")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(15)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(504.9600, 355.6319)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentX(0.4985)
layout:setPositionPercentY(0.4037)
layout:setVerticalEdge(3)
layout:setLeftMargin(504.9600)
layout:setRightMargin(508.0400)
layout:setTopMargin(525.2992)
layout:setBottomMargin(355.6319)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1:runAction(innerProject.animation)
Image_content:addChild(FileNode_1)

--Create Image_desc
local Image_desc = ccui.ImageView:create()
Image_desc:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hotupdate/hotupdate_plist.plist")
Image_desc:loadTexture("hotud_desc_bg.png",1)
Image_desc:setScale9Enabled(true)
Image_desc:setCapInsets({x = 42, y = 43, width = 46, height = 45})
Image_desc:setLayoutComponentEnabled(true)
Image_desc:setName("Image_desc")
Image_desc:setTag(22)
Image_desc:setCascadeColorEnabled(true)
Image_desc:setCascadeOpacityEnabled(true)
Image_desc:setPosition(506.5001, 145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_desc)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1646)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3292)
layout:setSize({width = 1013.0000, height = 290.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(0.0001)
layout:setRightMargin(-0.0001)
layout:setTopMargin(590.9310)
Image_content:addChild(Image_desc)

--Create Image_seg
local Image_seg = ccui.ImageView:create()
Image_seg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hotupdate/hotupdate_plist.plist")
Image_seg:loadTexture("hotud_segline.png",1)
Image_seg:setLayoutComponentEnabled(true)
Image_seg:setName("Image_seg")
Image_seg:setTag(21)
Image_seg:setCascadeColorEnabled(true)
Image_seg:setCascadeOpacityEnabled(true)
Image_seg:setPosition(500.6313, 291.4736)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_seg)
layout:setPositionPercentX(0.4942)
layout:setPositionPercentY(1.0051)
layout:setPercentWidth(0.9714)
layout:setPercentHeight(0.0793)
layout:setSize({width = 984.0000, height = 23.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(8.6313)
layout:setRightMargin(20.3687)
layout:setTopMargin(-12.9736)
layout:setBottomMargin(279.9736)
Image_desc:addChild(Image_seg)

--Create ScrollView_content
local ScrollView_content = ccui.ScrollView:create()
ScrollView_content:setBounceEnabled(true)
ScrollView_content:setInnerContainerSize({width = 1013, height = 429})
ScrollView_content:ignoreContentAdaptWithSize(false)
ScrollView_content:setClippingEnabled(true)
ScrollView_content:setBackGroundColorOpacity(114)
ScrollView_content:setLayoutComponentEnabled(true)
ScrollView_content:setName("ScrollView_content")
ScrollView_content:setTag(37)
ScrollView_content:setCascadeColorEnabled(true)
ScrollView_content:setCascadeOpacityEnabled(true)
ScrollView_content:setAnchorPoint(0.5000, 0.5000)
ScrollView_content:setPosition(504.0005, 145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ScrollView_content)
layout:setPositionPercentX(0.4975)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9674)
layout:setPercentHeight(0.8966)
layout:setSize({width = 980.0000, height = 260.0000})
layout:setLeftMargin(14.0006)
layout:setRightMargin(18.9995)
layout:setTopMargin(15.0000)
layout:setBottomMargin(15.0000)
Image_desc:addChild(ScrollView_content)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

