--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1040.0000, height = 938.0000})

--Create no_history
local no_history = cc.Sprite:create("hall/match/match_mate_bg1.png")
no_history:setName("no_history")
no_history:setTag(338)
no_history:setCascadeColorEnabled(true)
no_history:setCascadeOpacityEnabled(true)
no_history:setPosition(521.4346, 522.2631)
layout = ccui.LayoutComponent:bindLayoutComponent(no_history)
layout:setPositionPercentX(0.5014)
layout:setPositionPercentY(0.5568)
layout:setPercentWidth(0.9808)
layout:setPercentHeight(0.8625)
layout:setSize({width = 1020.0000, height = 809.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(11.4346)
layout:setRightMargin(8.5654)
layout:setTopMargin(11.2369)
layout:setBottomMargin(117.7631)
no_history:setBlendFunc({src = 1, dst = 771})
Layer:addChild(no_history)

--Create store_mm_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
local store_mm_2 = cc.Sprite:createWithSpriteFrameName("store_mm.png")
store_mm_2:setName("store_mm_2")
store_mm_2:setTag(353)
store_mm_2:setCascadeColorEnabled(true)
store_mm_2:setCascadeOpacityEnabled(true)
store_mm_2:setPosition(509.9995, 543.7014)
layout = ccui.LayoutComponent:bindLayoutComponent(store_mm_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6721)
layout:setPercentWidth(0.4706)
layout:setPercentHeight(0.5056)
layout:setSize({width = 480.0000, height = 409.0000})
layout:setLeftMargin(269.9995)
layout:setRightMargin(270.0005)
layout:setTopMargin(60.7986)
layout:setBottomMargin(339.2014)
store_mm_2:setBlendFunc({src = 1, dst = 771})
no_history:addChild(store_mm_2)

--Create siren_txt_no_history_3
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/siren/siren_plist.plist")
local siren_txt_no_history_3 = cc.Sprite:createWithSpriteFrameName("siren_txt_no_history.png")
siren_txt_no_history_3:setName("siren_txt_no_history_3")
siren_txt_no_history_3:setTag(354)
siren_txt_no_history_3:setCascadeColorEnabled(true)
siren_txt_no_history_3:setCascadeOpacityEnabled(true)
siren_txt_no_history_3:setPosition(509.9999, 246.3740)
layout = ccui.LayoutComponent:bindLayoutComponent(siren_txt_no_history_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3045)
layout:setPercentWidth(0.3324)
layout:setPercentHeight(0.1347)
layout:setSize({width = 339.0000, height = 109.0000})
layout:setLeftMargin(340.4999)
layout:setRightMargin(340.5001)
layout:setTopMargin(508.1260)
layout:setBottomMargin(191.8740)
siren_txt_no_history_3:setBlendFunc({src = 1, dst = 771})
no_history:addChild(siren_txt_no_history_3)

--Create btn_create_room
local btn_create_room = ccui.Button:create()
btn_create_room:ignoreContentAdaptWithSize(false)
btn_create_room:loadTextureNormal("common/common_btn_red_1.png",0)
btn_create_room:loadTexturePressed("common/common_btn_red_1.png",0)
btn_create_room:loadTextureDisabled("Default/Button_Disable.png",0)
btn_create_room:setTitleFontName("FZZhengHeiS-B-GB.ttf")
btn_create_room:setTitleFontSize(42)
btn_create_room:setTitleText("创建房间")
btn_create_room:setScale9Enabled(true)
btn_create_room:setCapInsets({x = 15, y = 11, width = 363, height = 91})
btn_create_room:setLayoutComponentEnabled(true)
btn_create_room:setName("btn_create_room")
btn_create_room:setTag(356)
btn_create_room:setCascadeColorEnabled(true)
btn_create_room:setCascadeOpacityEnabled(true)
btn_create_room:setPosition(519.9998, 73.1491)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_create_room)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0780)
layout:setPercentWidth(0.3779)
layout:setPercentHeight(0.1205)
layout:setSize({width = 393.0000, height = 113.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(323.4998)
layout:setRightMargin(323.5002)
layout:setTopMargin(808.3509)
layout:setBottomMargin(16.6491)
Layer:addChild(btn_create_room)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

