--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_bg:loadTexture("setting_bg.png",1)
Image_bg:setScale9Enabled(true)
Image_bg:setCapInsets({x = 343, y = 353, width = 354, height = 364})
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(87)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(1400.0000, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.7292)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5417)
layout:setPercentHeight(0.9907)
layout:setSize({width = 1040.0000, height = 1070.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(880.0000)
layout:setTopMargin(5.0000)
layout:setBottomMargin(5.0000)
layout:setStretchHeightEnabled(true)
Layer:addChild(Image_bg)

--Create Image_content
local Image_content = ccui.ImageView:create()
Image_content:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_content:loadTexture("setting_mask_bg.png",1)
Image_content:setScale9Enabled(true)
Image_content:setCapInsets({x = 45, y = 45, width = 12, height = 12})
Image_content:setTouchEnabled(true);
Image_content:setLayoutComponentEnabled(true)
Image_content:setName("Image_content")
Image_content:setTag(88)
Image_content:setCascadeColorEnabled(true)
Image_content:setCascadeOpacityEnabled(true)
Image_content:setPosition(518.9547, 478.0457)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_content)
layout:setPositionPercentX(0.4990)
layout:setPositionPercentY(0.4468)
layout:setPercentWidth(0.9740)
layout:setPercentHeight(0.8411)
layout:setSize({width = 1013.0000, height = 899.9770})
layout:setVerticalEdge(1)
layout:setLeftMargin(12.4547)
layout:setRightMargin(14.5453)
layout:setTopMargin(141.9658)
layout:setBottomMargin(28.0572)
layout:setStretchHeightEnabled(true)
Image_bg:addChild(Image_content)

--Create Image_header
local Image_header = ccui.ImageView:create()
Image_header:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_header:loadTexture("setting_top.png",1)
Image_header:setLayoutComponentEnabled(true)
Image_header:setName("Image_header")
Image_header:setTag(89)
Image_header:setCascadeColorEnabled(true)
Image_header:setCascadeOpacityEnabled(true)
Image_header:setPosition(519.4295, 999.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_header)
layout:setPositionPercentX(0.4995)
layout:setPositionPercentY(0.9336)
layout:setPercentWidth(1.0144)
layout:setPercentHeight(0.1327)
layout:setSize({width = 1055.0000, height = 142.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(-8.0705)
layout:setRightMargin(-6.9294)
layout:setBottomMargin(928.0000)
Image_bg:addChild(Image_header)

--Create Image_choosetag
local Image_choosetag = ccui.ImageView:create()
Image_choosetag:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_choosetag:loadTexture("store_choose_tag1.png",1)
Image_choosetag:setTouchEnabled(true);
Image_choosetag:setLayoutComponentEnabled(true)
Image_choosetag:setName("Image_choosetag")
Image_choosetag:setTag(377)
Image_choosetag:setCascadeColorEnabled(true)
Image_choosetag:setCascadeOpacityEnabled(true)
Image_choosetag:setPosition(280.1981, 55.5980)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_choosetag)
layout:setPositionPercentX(0.2656)
layout:setPositionPercentY(0.3915)
layout:setPercentWidth(0.2597)
layout:setPercentHeight(1.1620)
layout:setSize({width = 274.0000, height = 165.0000})
layout:setLeftMargin(143.1981)
layout:setRightMargin(637.8019)
layout:setTopMargin(3.9020)
layout:setBottomMargin(-26.9020)
Image_header:addChild(Image_choosetag)

--Create Image_tag
local Image_tag = ccui.ImageView:create()
Image_tag:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_tag:loadTexture("store_choose_tag2.png",1)
Image_tag:setTouchEnabled(true);
Image_tag:setLayoutComponentEnabled(true)
Image_tag:setName("Image_tag")
Image_tag:setTag(378)
Image_tag:setCascadeColorEnabled(true)
Image_tag:setCascadeOpacityEnabled(true)
Image_tag:setPosition(137.0000, 151.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tag)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9182)
layout:setPercentWidth(0.6314)
layout:setPercentHeight(0.1636)
layout:setSize({width = 173.0000, height = 27.0000})
layout:setLeftMargin(50.5000)
layout:setRightMargin(50.5000)
layout:setBottomMargin(138.0000)
Image_choosetag:addChild(Image_tag)

--Create Panel_FAQ
local Panel_FAQ = ccui.Layout:create()
Panel_FAQ:ignoreContentAdaptWithSize(false)
Panel_FAQ:setClippingEnabled(false)
Panel_FAQ:setTouchEnabled(true);
Panel_FAQ:setLayoutComponentEnabled(true)
Panel_FAQ:setName("Panel_FAQ")
Panel_FAQ:setTag(379)
Panel_FAQ:setCascadeColorEnabled(true)
Panel_FAQ:setCascadeOpacityEnabled(true)
Panel_FAQ:setAnchorPoint(0.5000, 0.5000)
Panel_FAQ:setPosition(278.9603, 86.1000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_FAQ)
layout:setPositionPercentX(0.2644)
layout:setPositionPercentY(0.6063)
layout:setPercentWidth(0.4739)
layout:setPercentHeight(0.7042)
layout:setSize({width = 500.0000, height = 100.0000})
layout:setLeftMargin(28.9603)
layout:setRightMargin(526.0397)
layout:setTopMargin(5.9000)
layout:setBottomMargin(36.1000)
Image_header:addChild(Panel_FAQ)

--Create Text_FAQ
local Text_FAQ = ccui.Text:create()
Text_FAQ:ignoreContentAdaptWithSize(true)
Text_FAQ:setTextAreaSize({width = 0, height = 0})
Text_FAQ:setFontName("FZZhengHeiS-B-GB.ttf")
Text_FAQ:setFontSize(48)
Text_FAQ:setString([[常见问题]])
Text_FAQ:setTextHorizontalAlignment(1)
Text_FAQ:setTextVerticalAlignment(1)
Text_FAQ:setLayoutComponentEnabled(true)
Text_FAQ:setName("Text_FAQ")
Text_FAQ:setTag(380)
Text_FAQ:setCascadeColorEnabled(true)
Text_FAQ:setCascadeOpacityEnabled(true)
Text_FAQ:setPosition(246.7700, 35.4087)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_FAQ)
layout:setPositionPercentX(0.4935)
layout:setPositionPercentY(0.3541)
layout:setPercentWidth(0.3860)
layout:setPercentHeight(0.5900)
layout:setSize({width = 193.0000, height = 59.0000})
layout:setLeftMargin(150.2700)
layout:setRightMargin(156.7300)
layout:setTopMargin(35.0913)
layout:setBottomMargin(5.9087)
Panel_FAQ:addChild(Text_FAQ)

--Create Image_seg
local Image_seg = ccui.ImageView:create()
Image_seg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_seg:loadTexture("store_seg_line_title.png",1)
Image_seg:setTouchEnabled(true);
Image_seg:setLayoutComponentEnabled(true)
Image_seg:setName("Image_seg")
Image_seg:setTag(381)
Image_seg:setCascadeColorEnabled(true)
Image_seg:setCascadeOpacityEnabled(true)
Image_seg:setPosition(500.0000, 49.5174)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_seg)
layout:setPositionPercentX(1.0000)
layout:setPositionPercentY(0.4952)
layout:setPercentWidth(0.0040)
layout:setPercentHeight(0.6900)
layout:setSize({width = 2.0000, height = 69.0000})
layout:setLeftMargin(499.0000)
layout:setRightMargin(-1.0000)
layout:setTopMargin(15.9826)
layout:setBottomMargin(15.0174)
Panel_FAQ:addChild(Image_seg)

--Create Panel_Guandan
local Panel_Guandan = ccui.Layout:create()
Panel_Guandan:ignoreContentAdaptWithSize(false)
Panel_Guandan:setClippingEnabled(false)
Panel_Guandan:setTouchEnabled(true);
Panel_Guandan:setLayoutComponentEnabled(true)
Panel_Guandan:setName("Panel_Guandan")
Panel_Guandan:setTag(382)
Panel_Guandan:setCascadeColorEnabled(true)
Panel_Guandan:setCascadeOpacityEnabled(true)
Panel_Guandan:setAnchorPoint(0.5000, 0.5000)
Panel_Guandan:setPosition(781.5334, 86.1000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_Guandan)
layout:setPositionPercentX(0.7408)
layout:setPositionPercentY(0.6063)
layout:setPercentWidth(0.4739)
layout:setPercentHeight(0.7042)
layout:setSize({width = 500.0000, height = 100.0000})
layout:setLeftMargin(531.5334)
layout:setRightMargin(23.4666)
layout:setTopMargin(5.9000)
layout:setBottomMargin(36.1000)
Image_header:addChild(Panel_Guandan)

--Create Text_Guandan
local Text_Guandan = ccui.Text:create()
Text_Guandan:ignoreContentAdaptWithSize(true)
Text_Guandan:setTextAreaSize({width = 0, height = 0})
Text_Guandan:setFontName("FZZhengHeiS-B-GB.ttf")
Text_Guandan:setFontSize(48)
Text_Guandan:setString([[掼蛋]])
Text_Guandan:setTextHorizontalAlignment(1)
Text_Guandan:setTextVerticalAlignment(1)
Text_Guandan:setLayoutComponentEnabled(true)
Text_Guandan:setName("Text_Guandan")
Text_Guandan:setTag(383)
Text_Guandan:setCascadeColorEnabled(true)
Text_Guandan:setCascadeOpacityEnabled(true)
Text_Guandan:setPosition(246.7667, 35.4087)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Guandan)
layout:setPositionPercentX(0.4935)
layout:setPositionPercentY(0.3541)
layout:setPercentWidth(0.1940)
layout:setPercentHeight(0.5900)
layout:setSize({width = 97.0000, height = 59.0000})
layout:setLeftMargin(198.2667)
layout:setRightMargin(204.7333)
layout:setTopMargin(35.0913)
layout:setBottomMargin(5.9087)
Panel_Guandan:addChild(Text_Guandan)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

