--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ImageD
local ImageD = ccui.ImageView:create()
ImageD:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
ImageD:loadTexture("email_message.png",1)
ImageD:setScale9Enabled(true)
ImageD:setCapInsets({x = 220, y = 15, width = 1, height = 67})
ImageD:setTouchEnabled(true);
ImageD:setLayoutComponentEnabled(true)
ImageD:setName("ImageD")
ImageD:setTag(104)
ImageD:setCascadeColorEnabled(true)
ImageD:setCascadeOpacityEnabled(true)
ImageD:setAnchorPoint(0.5000, 1.0000)
ImageD:setPosition(0.0001, 1.5012)
layout = ccui.LayoutComponent:bindLayoutComponent(ImageD)
layout:setSize({width = 952.0000, height = 152.0000})
layout:setLeftMargin(-475.9999)
layout:setRightMargin(-476.0001)
layout:setTopMargin(-1.5012)
layout:setBottomMargin(-150.4988)
Node:addChild(ImageD)

--Create Image_icon
local Image_icon = ccui.ImageView:create()
Image_icon:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
Image_icon:loadTexture("email_envelopeClose.png",1)
Image_icon:setLayoutComponentEnabled(true)
Image_icon:setName("Image_icon")
Image_icon:setTag(105)
Image_icon:setCascadeColorEnabled(true)
Image_icon:setCascadeOpacityEnabled(true)
Image_icon:setAnchorPoint(0.0000, 1.0000)
Image_icon:setPosition(10.8636, 140.4007)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_icon)
layout:setPositionPercentX(0.0114)
layout:setPositionPercentY(0.9237)
layout:setPercentWidth(0.1261)
layout:setPercentHeight(0.7895)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(10.8636)
layout:setRightMargin(821.1364)
layout:setTopMargin(11.5993)
layout:setBottomMargin(20.4007)
ImageD:addChild(Image_icon)

--Create Image_fujian
local Image_fujian = ccui.ImageView:create()
Image_fujian:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
Image_fujian:loadTexture("email_Enclosure.png",1)
Image_fujian:setLayoutComponentEnabled(true)
Image_fujian:setName("Image_fujian")
Image_fujian:setTag(106)
Image_fujian:setCascadeColorEnabled(true)
Image_fujian:setCascadeOpacityEnabled(true)
Image_fujian:setAnchorPoint(0.5000, 1.0000)
Image_fujian:setPosition(880.0000, 160.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_fujian)
layout:setPositionPercentX(0.9244)
layout:setPositionPercentY(1.0526)
layout:setPercentWidth(0.0903)
layout:setPercentHeight(0.3684)
layout:setSize({width = 86.0000, height = 56.0000})
layout:setLeftMargin(837.0000)
layout:setRightMargin(29.0000)
layout:setTopMargin(-8.0000)
layout:setBottomMargin(104.0000)
ImageD:addChild(Image_fujian)

--Create title
local title = ccui.Text:create()
title:ignoreContentAdaptWithSize(true)
title:setTextAreaSize({width = 0, height = 0})
title:setFontName("FZZhengHeiS-B-GB.ttf")
title:setFontSize(42)
title:setString([[新版本上线啦！]])
title:setLayoutComponentEnabled(true)
title:setName("title")
title:setTag(107)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
title:setAnchorPoint(0.0000, 1.0000)
title:setPosition(159.7158, 126.0892)
title:setTextColor({r = 38, g = 47, b = 42})
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setPositionPercentX(0.1678)
layout:setPositionPercentY(0.8295)
layout:setPercentWidth(0.2826)
layout:setPercentHeight(0.3355)
layout:setSize({width = 269.0000, height = 51.0000})
layout:setLeftMargin(159.7158)
layout:setRightMargin(523.2842)
layout:setTopMargin(25.9108)
layout:setBottomMargin(75.0892)
ImageD:addChild(title)

--Create content
local content = ccui.Text:create()
content:ignoreContentAdaptWithSize(false)
content:setFontName("FZZhengHeiS-B-GB.ttf")
content:setFontSize(30)
content:setString([[老板，新的版本已经上线！增加了asd]])
content:setLayoutComponentEnabled(true)
content:setName("content")
content:setTag(114)
content:setCascadeColorEnabled(true)
content:setCascadeOpacityEnabled(true)
content:setAnchorPoint(0.0000, 1.0000)
content:setPosition(158.3907, 61.9415)
content:setTextColor({r = 126, g = 110, b = 68})
layout = ccui.LayoutComponent:bindLayoutComponent(content)
layout:setPositionPercentX(0.1664)
layout:setPositionPercentY(0.4075)
layout:setPercentWidth(0.4727)
layout:setPercentHeight(0.2434)
layout:setSize({width = 450.0000, height = 37.0000})
layout:setLeftMargin(158.3907)
layout:setRightMargin(343.6093)
layout:setTopMargin(90.0585)
layout:setBottomMargin(24.9415)
ImageD:addChild(content)

--Create Image_open
local Image_open = ccui.ImageView:create()
Image_open:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
Image_open:loadTexture("email_close.png",1)
Image_open:setLayoutComponentEnabled(true)
Image_open:setName("Image_open")
Image_open:setTag(109)
Image_open:setCascadeColorEnabled(true)
Image_open:setCascadeOpacityEnabled(true)
Image_open:setPosition(628.2722, 45.3898)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_open)
layout:setPositionPercentX(0.6599)
layout:setPositionPercentY(0.2986)
layout:setPercentWidth(0.0179)
layout:setPercentHeight(0.0921)
layout:setSize({width = 17.0000, height = 14.0000})
layout:setLeftMargin(619.7722)
layout:setRightMargin(315.2278)
layout:setTopMargin(99.6102)
layout:setBottomMargin(38.3898)
ImageD:addChild(Image_open)

--Create Image_leftTime
local Image_leftTime = ccui.ImageView:create()
Image_leftTime:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
Image_leftTime:loadTexture("email_lasttime.png",1)
Image_leftTime:setLayoutComponentEnabled(true)
Image_leftTime:setName("Image_leftTime")
Image_leftTime:setTag(110)
Image_leftTime:setCascadeColorEnabled(true)
Image_leftTime:setCascadeOpacityEnabled(true)
Image_leftTime:setPosition(829.4252, 46.3946)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_leftTime)
layout:setPositionPercentX(0.8712)
layout:setPositionPercentY(0.3052)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(0.3355)
layout:setSize({width = 238.0000, height = 51.0000})
layout:setLeftMargin(710.4252)
layout:setRightMargin(3.5748)
layout:setTopMargin(80.1054)
layout:setBottomMargin(20.8946)
ImageD:addChild(Image_leftTime)

--Create time
local time = ccui.Text:create()
time:ignoreContentAdaptWithSize(true)
time:setTextAreaSize({width = 0, height = 0})
time:setFontName("FZZhengHeiS-B-GB.ttf")
time:setFontSize(26)
time:setString([[剩余时间：30天]])
time:setLayoutComponentEnabled(true)
time:setName("time")
time:setTag(111)
time:setCascadeColorEnabled(true)
time:setCascadeOpacityEnabled(true)
time:setAnchorPoint(0.0000, 0.5000)
time:setPosition(34.0762, 23.5147)
time:setTextColor({r = 244, g = 255, b = 229})
layout = ccui.LayoutComponent:bindLayoutComponent(time)
layout:setPositionPercentX(0.1432)
layout:setPositionPercentY(0.4611)
layout:setPercentWidth(0.8193)
layout:setPercentHeight(0.6275)
layout:setSize({width = 195.0000, height = 32.0000})
layout:setLeftMargin(34.0762)
layout:setRightMargin(8.9238)
layout:setTopMargin(11.4853)
layout:setBottomMargin(7.5147)
Image_leftTime:addChild(time)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

