--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ImageD
local ImageD = ccui.ImageView:create()
ImageD:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
ImageD:loadTexture("email_message.png",1)
ImageD:setScale9Enabled(true)
ImageD:setCapInsets({x = 220, y = 15, width = 1, height = 67})
ImageD:setTouchEnabled(true);
ImageD:setLayoutComponentEnabled(true)
ImageD:setName("ImageD")
ImageD:setTag(301)
ImageD:setCascadeColorEnabled(true)
ImageD:setCascadeOpacityEnabled(true)
ImageD:setAnchorPoint(0.5000, 1.0000)
ImageD:setPosition(0.0001, 1.5012)
layout = ccui.LayoutComponent:bindLayoutComponent(ImageD)
layout:setSize({width = 952.0000, height = 400.0000})
layout:setLeftMargin(-475.9999)
layout:setRightMargin(-476.0001)
layout:setTopMargin(-1.5012)
layout:setBottomMargin(-398.4988)
Node:addChild(ImageD)

--Create Image_icon
local Image_icon = ccui.ImageView:create()
Image_icon:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
Image_icon:loadTexture("email_envelopeOpen.png",1)
Image_icon:setLayoutComponentEnabled(true)
Image_icon:setName("Image_icon")
Image_icon:setTag(302)
Image_icon:setCascadeColorEnabled(true)
Image_icon:setCascadeOpacityEnabled(true)
Image_icon:setAnchorPoint(0.0000, 1.0000)
Image_icon:setPosition(10.0000, 391.8198)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_icon)
layout:setPositionPercentX(0.0105)
layout:setPositionPercentY(0.9795)
layout:setPercentWidth(0.1261)
layout:setPercentHeight(0.3000)
layout:setSize({width = 120.0000, height = 120.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(822.0000)
layout:setTopMargin(8.1802)
layout:setBottomMargin(271.8198)
ImageD:addChild(Image_icon)

--Create title
local title = ccui.Text:create()
title:ignoreContentAdaptWithSize(true)
title:setTextAreaSize({width = 0, height = 0})
title:setFontName("FZZhengHeiS-B-GB.ttf")
title:setFontSize(42)
title:setString([[新版本上线啦！]])
title:setLayoutComponentEnabled(true)
title:setName("title")
title:setTag(303)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
title:setAnchorPoint(0.0000, 1.0000)
title:setPosition(154.0000, 388.8199)
title:setTextColor({r = 38, g = 47, b = 42})
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setPositionPercentX(0.1618)
layout:setPositionPercentY(0.9720)
layout:setPercentWidth(0.2826)
layout:setPercentHeight(0.1275)
layout:setSize({width = 269.0000, height = 51.0000})
layout:setLeftMargin(154.0000)
layout:setRightMargin(529.0000)
layout:setTopMargin(11.1801)
layout:setBottomMargin(337.8199)
ImageD:addChild(title)

--Create content
local content = ccui.Text:create()
content:ignoreContentAdaptWithSize(false)
content:setFontName("FZZhengHeiS-B-GB.ttf")
content:setFontSize(30)
content:setString([[]])
content:setLayoutComponentEnabled(true)
content:setName("content")
content:setTag(304)
content:setCascadeColorEnabled(true)
content:setCascadeOpacityEnabled(true)
content:setAnchorPoint(0.0000, 1.0000)
content:setPosition(157.6364, 319.0182)
content:setTextColor({r = 126, g = 110, b = 68})
layout = ccui.LayoutComponent:bindLayoutComponent(content)
layout:setPositionPercentX(0.1656)
layout:setPositionPercentY(0.7975)
layout:setPercentWidth(0.7668)
layout:setPercentHeight(0.0750)
layout:setSize({width = 730.0000, height = 30.0000})
layout:setLeftMargin(157.6364)
layout:setRightMargin(64.3636)
layout:setTopMargin(80.9818)
layout:setBottomMargin(289.0182)
ImageD:addChild(content)

--Create Image_open
local Image_open = ccui.ImageView:create()
Image_open:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
Image_open:loadTexture("email_open.png",1)
Image_open:setLayoutComponentEnabled(true)
Image_open:setName("Image_open")
Image_open:setTag(305)
Image_open:setCascadeColorEnabled(true)
Image_open:setCascadeOpacityEnabled(true)
Image_open:setAnchorPoint(0.0000, 0.0000)
Image_open:setPosition(891.8000, 36.9318)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_open)
layout:setPositionPercentX(0.9368)
layout:setPositionPercentY(0.0923)
layout:setPercentWidth(0.0179)
layout:setPercentHeight(0.0350)
layout:setSize({width = 17.0000, height = 14.0000})
layout:setLeftMargin(891.8000)
layout:setRightMargin(43.2000)
layout:setTopMargin(349.0682)
layout:setBottomMargin(36.9318)
ImageD:addChild(Image_open)

--Create fujian
local fujian = ccui.ImageView:create()
fujian:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
fujian:loadTexture("email_Enclosure.png",1)
fujian:setLayoutComponentEnabled(true)
fujian:setName("fujian")
fujian:setTag(307)
fujian:setCascadeColorEnabled(true)
fujian:setCascadeOpacityEnabled(true)
fujian:setAnchorPoint(0.5000, 1.0000)
fujian:setPosition(880.0001, 408.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(fujian)
layout:setPositionPercentX(0.9244)
layout:setPositionPercentY(1.0200)
layout:setPercentWidth(0.0903)
layout:setPercentHeight(0.1400)
layout:setSize({width = 86.0000, height = 56.0000})
layout:setLeftMargin(837.0001)
layout:setRightMargin(28.9999)
layout:setTopMargin(-8.0000)
layout:setBottomMargin(352.0000)
ImageD:addChild(fujian)

--Create Image_6
local Image_6 = ccui.ImageView:create()
Image_6:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
Image_6:loadTexture("email_shadow.png",1)
Image_6:setLayoutComponentEnabled(true)
Image_6:setName("Image_6")
Image_6:setTag(39)
Image_6:setCascadeColorEnabled(true)
Image_6:setCascadeOpacityEnabled(true)
Image_6:setPosition(513.7512, 127.4648)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_6)
layout:setPositionPercentX(0.5397)
layout:setPositionPercentY(0.3187)
layout:setPercentWidth(0.7889)
layout:setPercentHeight(0.3550)
layout:setSize({width = 751.0000, height = 142.0000})
layout:setLeftMargin(138.2512)
layout:setRightMargin(62.7488)
layout:setTopMargin(201.5352)
layout:setBottomMargin(56.4648)
ImageD:addChild(Image_6)

--Create get
local get = ccui.Button:create()
get:ignoreContentAdaptWithSize(false)
get:loadTextureNormal("common/common_btn_yellow3.png",0)
get:setTitleFontName("FZZhengHeiS-B-GB.ttf")
get:setTitleFontSize(55)
get:setTitleText("领取")
get:setTitleColor({r = 141, g = 32, b = 18})
get:setScale9Enabled(true)
get:setCapInsets({x = 15, y = 11, width = 208, height = 78})
get:setLayoutComponentEnabled(true)
get:setName("get")
get:setTag(308)
get:setCascadeColorEnabled(true)
get:setCascadeOpacityEnabled(true)
get:setPosition(818.3448, 125.0700)
layout = ccui.LayoutComponent:bindLayoutComponent(get)
layout:setPositionPercentX(0.8596)
layout:setPositionPercentY(0.3127)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(0.2500)
layout:setSize({width = 238.0000, height = 100.0000})
layout:setLeftMargin(699.3448)
layout:setRightMargin(14.6552)
layout:setTopMargin(224.9300)
layout:setBottomMargin(75.0700)
ImageD:addChild(get)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/email/email_plist.plist")
Image_1:loadTexture("email_item.png",1)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(130)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(210.6572, 125.0700)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.2213)
layout:setPositionPercentY(0.3127)
layout:setPercentWidth(0.1176)
layout:setPercentHeight(0.2800)
layout:setSize({width = 112.0000, height = 112.0000})
layout:setLeftMargin(154.6572)
layout:setRightMargin(685.3428)
layout:setTopMargin(218.9300)
layout:setBottomMargin(69.0700)
ImageD:addChild(Image_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

