--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create aloneGame_btn_1
local aloneGame_btn_1 = cc.Sprite:create("login/test/aloneGame_btn.png")
aloneGame_btn_1:setName("aloneGame_btn_1")
aloneGame_btn_1:setTag(9)
aloneGame_btn_1:setCascadeColorEnabled(true)
aloneGame_btn_1:setCascadeOpacityEnabled(true)
aloneGame_btn_1:setPosition(521.0000, 335.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(aloneGame_btn_1)
layout:setPositionPercentX(0.4070)
layout:setPositionPercentY(0.4653)
layout:setPercentWidth(0.0875)
layout:setPercentHeight(0.1556)
layout:setSize({width = 112.0000, height = 112.0000})
layout:setLeftMargin(465.0000)
layout:setRightMargin(703.0000)
layout:setTopMargin(329.0000)
layout:setBottomMargin(279.0000)
aloneGame_btn_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(aloneGame_btn_1)

--Create btn_laizi_3_2
local btn_laizi_3_2 = cc.Sprite:create("login/test/btn_laizi_3.png")
btn_laizi_3_2:setName("btn_laizi_3_2")
btn_laizi_3_2:setTag(10)
btn_laizi_3_2:setCascadeColorEnabled(true)
btn_laizi_3_2:setCascadeOpacityEnabled(true)
btn_laizi_3_2:setPosition(734.0000, 383.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_laizi_3_2)
layout:setPositionPercentX(0.5734)
layout:setPositionPercentY(0.5319)
layout:setPercentWidth(0.2250)
layout:setPercentHeight(0.5375)
layout:setSize({width = 288.0000, height = 387.0000})
layout:setLeftMargin(590.0000)
layout:setRightMargin(402.0000)
layout:setTopMargin(143.5000)
layout:setBottomMargin(189.5000)
btn_laizi_3_2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(btn_laizi_3_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

