--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1000.0000, height = 600.0000})

--Create btn_happy_5_1
local btn_happy_5_1 = cc.Sprite:create("login/test/btn_happy_5.png")
btn_happy_5_1:setName("btn_happy_5_1")
btn_happy_5_1:setTag(7)
btn_happy_5_1:setCascadeColorEnabled(true)
btn_happy_5_1:setCascadeOpacityEnabled(true)
btn_happy_5_1:setPosition(491.2220, 404.9004)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_happy_5_1)
layout:setPositionPercentX(0.4912)
layout:setPositionPercentY(0.6748)
layout:setPercentWidth(0.2880)
layout:setPercentHeight(0.6450)
layout:setSize({width = 288.0000, height = 387.0000})
layout:setLeftMargin(347.2220)
layout:setRightMargin(364.7780)
layout:setTopMargin(1.5996)
layout:setBottomMargin(211.4004)
btn_happy_5_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(btn_happy_5_1)

--Create duty_logo_box_2
local duty_logo_box_2 = cc.Sprite:create("login/test/duty_logo_box.png")
duty_logo_box_2:setName("duty_logo_box_2")
duty_logo_box_2:setTag(8)
duty_logo_box_2:setCascadeColorEnabled(true)
duty_logo_box_2:setCascadeOpacityEnabled(true)
duty_logo_box_2:setPosition(390.3724, 137.7716)
layout = ccui.LayoutComponent:bindLayoutComponent(duty_logo_box_2)
layout:setPositionPercentX(0.3904)
layout:setPositionPercentY(0.2296)
layout:setPercentWidth(0.1020)
layout:setPercentHeight(0.1700)
layout:setSize({width = 102.0000, height = 102.0000})
layout:setLeftMargin(339.3724)
layout:setRightMargin(558.6276)
layout:setTopMargin(411.2284)
layout:setBottomMargin(86.7716)
duty_logo_box_2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(duty_logo_box_2)

--Create duty_logo_cup_3
local duty_logo_cup_3 = cc.Sprite:create("login/test/duty_logo_cup.png")
duty_logo_cup_3:setName("duty_logo_cup_3")
duty_logo_cup_3:setTag(9)
duty_logo_cup_3:setCascadeColorEnabled(true)
duty_logo_cup_3:setCascadeOpacityEnabled(true)
duty_logo_cup_3:setPosition(595.5255, 141.3560)
layout = ccui.LayoutComponent:bindLayoutComponent(duty_logo_cup_3)
layout:setPositionPercentX(0.5955)
layout:setPositionPercentY(0.2356)
layout:setPercentWidth(0.1020)
layout:setPercentHeight(0.1700)
layout:setSize({width = 102.0000, height = 102.0000})
layout:setLeftMargin(544.5255)
layout:setRightMargin(353.4745)
layout:setTopMargin(407.6440)
layout:setBottomMargin(90.3560)
duty_logo_cup_3:setBlendFunc({src = 1, dst = 771})
Layer:addChild(duty_logo_cup_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

