--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel
local Panel = ccui.Layout:create()
Panel:ignoreContentAdaptWithSize(false)
Panel:setBackGroundImage("hall/hallcontent/hall_notice_bg.png",0)
Panel:setClippingEnabled(true)
Panel:setBackGroundColorOpacity(102)
Panel:setLayoutComponentEnabled(true)
Panel:setName("Panel")
Panel:setTag(68)
Panel:setCascadeColorEnabled(true)
Panel:setCascadeOpacityEnabled(true)
Panel:setPosition(-597.5416, -24.6169)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel)
layout:setSize({width = 1199.0000, height = 50.0000})
layout:setLeftMargin(-597.5416)
layout:setRightMargin(-601.4584)
layout:setTopMargin(-25.3831)
layout:setBottomMargin(-24.6169)
Node:addChild(Panel)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("hall/hallcontent/hall_notice_horn.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(67)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(-514.5573, 9.5088)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setSize({width = 85.0000, height = 85.0000})
layout:setLeftMargin(-557.0573)
layout:setRightMargin(472.0573)
layout:setTopMargin(-52.0088)
layout:setBottomMargin(-32.9912)
Node:addChild(Image_1)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(true)
Panel_2:setBackGroundColorOpacity(102)
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(163)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setPosition(-474.4395, -24.9942)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setSize({width = 950.0000, height = 50.0000})
layout:setLeftMargin(-474.4395)
layout:setRightMargin(-475.5605)
layout:setTopMargin(-25.0058)
layout:setBottomMargin(-24.9942)
Node:addChild(Panel_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

