local WhippedEggCfg = {}

WhippedEggCfg.innerEventComponent = nil
WhippedEggCfg.InnerEvents = {
	GD_EVENT_GAMESTART = "GD_EVENT_GAMESTART", --惯蛋游戏开局消息
	GD_EVENT_TRIBUTE = "GD_EVENT_TRIBUTE", --进贡消息
	GD_EVENT_EXCHANGECARD = "GD_EVENT_EXCHANGECARD", --交换牌消息
	GD_EVENT_PLAYCARD = "GD_EVENT_PLAYCARD", --打牌消息
	GD_EVENT_GAMEOVER = "GD_EVENT_GAMEOVER", --结束游戏消息
	GD_EVENT_RESUMEGAME = "GD_EVENT_RESUMEGAME", --恢复对局消息
	GD_EVENT_TABLESTATE = "GD_EVENT_TABLESTATE", --续局中玩家状态改变
	GD_EVENT_SUBSTITUTE = "GD_EVENT_SUBSTITUTE", --托管
	GD_EVENT_MATCH_HOLDAWARD = "GD_EVENT_MATCH_HOLDAWARD", --普通房间打到结算
	GD_EVENT_USERINFO_RESP = "GD_EVENT_USERINFO_RESP", --对局中玩家数据
	

	GD_EVENT_MATCH_GAMESTART = "GD_EVENT_MATCH_GAMESTART", --比赛开局
	GD_EVENT_MATCH_GAMEOVER = "GD_EVENT_MATCH_GAMEOVER", --比赛结算
	GD_EVENT_MATCH_RESUMEGAME = "GD_EVENT_MATCH_RESUMEGAME", --比赛恢复对局
}


return WhippedEggCfg