--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/firstCharge/firstCharge_plist.plist")
Image_bg:loadTexture("hall_fistCharge_item_bg.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(21)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(98.0000, 98.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 196.0000, height = 197.0000})
layout:setRightMargin(-196.0000)
layout:setTopMargin(-197.0000)
Node:addChild(Image_bg)

--Create Image_icon
local Image_icon = ccui.ImageView:create()
Image_icon:ignoreContentAdaptWithSize(false)
Image_icon:loadTexture("common/goods/item_10170998.png",0)
Image_icon:setLayoutComponentEnabled(true)
Image_icon:setName("Image_icon")
Image_icon:setTag(22)
Image_icon:setCascadeColorEnabled(true)
Image_icon:setCascadeOpacityEnabled(true)
Image_icon:setPosition(94.2835, 121.2368)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_icon)
layout:setPositionPercentX(0.4810)
layout:setPositionPercentY(0.6154)
layout:setPercentWidth(0.7857)
layout:setPercentHeight(0.7817)
layout:setSize({width = 154.0000, height = 154.0000})
layout:setLeftMargin(17.2835)
layout:setRightMargin(24.7165)
layout:setTopMargin(-1.2368)
layout:setBottomMargin(44.2368)
Image_bg:addChild(Image_icon)

--Create Text_amont
local Text_amont = ccui.Text:create()
Text_amont:ignoreContentAdaptWithSize(true)
Text_amont:setTextAreaSize({width = 0, height = 0})
Text_amont:setFontName("FZZhengHeiS-B-GB.ttf")
Text_amont:setFontSize(28)
Text_amont:setString([[0金币]])
Text_amont:setLayoutComponentEnabled(true)
Text_amont:setName("Text_amont")
Text_amont:setTag(23)
Text_amont:setCascadeColorEnabled(true)
Text_amont:setCascadeOpacityEnabled(true)
Text_amont:setPosition(95.2450, 25.5498)
Text_amont:setTextColor({r = 224, g = 224, b = 224})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_amont)
layout:setPositionPercentX(0.4859)
layout:setPositionPercentY(0.1297)
layout:setPercentWidth(0.3980)
layout:setPercentHeight(0.1726)
layout:setSize({width = 78.0000, height = 34.0000})
layout:setLeftMargin(56.2450)
layout:setRightMargin(61.7550)
layout:setTopMargin(154.4502)
layout:setBottomMargin(8.5498)
Image_bg:addChild(Text_amont)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

