local registry = {
    "hall.fsm.cfg.UIRootCfg",
    "hall.fsm.cfg.UiSignCfg",
    "hall.fsm.cfg.UISettingCfg",
    "hall.fsm.cfg.UIChooseRoomCfg",
    "hall.fsm.cfg.UISiRenRoomCfg",
    "hall.fsm.cfg.UIStoreCfg",
    "hall.fsm.cfg.UIMatchCfg",
    "hall.fsm.cfg.UIEmailCfg",
    "hall.fsm.cfg.UIUserInfoCfg",
    "hall.fsm.cfg.UIExchangeCfg",
    "hall.fsm.cfg.UITaskCfg",
    "hall.fsm.cfg.UIActivityCfg",
    "hall.fsm.cfg.UIRankCfg",
    "hall.fsm.cfg.UIGoodsBoxCfg",
    "hall.fsm.cfg.UIFirstChargeCfg",
	"hall.fsm.cfg.UICardPartnerCfg",
	"hall.fsm.cfg.UIRoomChatCfg",
	"hall.fsm.cfg.UISiRenInvitedCfg",
}
return registry