--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("common/exit.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(424)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(959.9998, 617.9943)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5722)
layout:setPercentWidth(0.5792)
layout:setPercentHeight(0.3194)
layout:setSize({width = 1112.0000, height = 345.0000})
layout:setLeftMargin(403.9998)
layout:setRightMargin(404.0002)
layout:setTopMargin(289.5057)
layout:setBottomMargin(445.4943)
Layer:addChild(Image_1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("FZZhengHeiS-B-GB.ttf")
Text_1:setFontSize(50)
Text_1:setString([[真的要离开吗？]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(427)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(654.8403, 197.3946)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.5889)
layout:setPositionPercentY(0.5722)
layout:setPercentWidth(0.2977)
layout:setPercentHeight(0.1768)
layout:setSize({width = 331.0000, height = 61.0000})
layout:setLeftMargin(489.3403)
layout:setRightMargin(291.6597)
layout:setTopMargin(117.1054)
layout:setBottomMargin(166.8946)
Image_1:addChild(Text_1)

--Create Text_1_0
local Text_1_0 = ccui.Text:create()
Text_1_0:ignoreContentAdaptWithSize(true)
Text_1_0:setTextAreaSize({width = 0, height = 0})
Text_1_0:setFontName("FZZhengHeiS-B-GB.ttf")
Text_1_0:setFontSize(40)
Text_1_0:setString([[真的要离开吗？]])
Text_1_0:setLayoutComponentEnabled(true)
Text_1_0:setName("Text_1_0")
Text_1_0:setTag(428)
Text_1_0:setCascadeColorEnabled(true)
Text_1_0:setCascadeOpacityEnabled(true)
Text_1_0:setPosition(653.7704, 133.6226)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_0)
layout:setPositionPercentX(0.5879)
layout:setPositionPercentY(0.3873)
layout:setPercentWidth(0.2392)
layout:setPercentHeight(0.1420)
layout:setSize({width = 266.0000, height = 49.0000})
layout:setLeftMargin(520.7704)
layout:setRightMargin(325.2296)
layout:setTopMargin(186.8774)
layout:setBottomMargin(109.1226)
Image_1:addChild(Text_1_0)

--Create btnContinue
local btnContinue = ccui.Button:create()
btnContinue:ignoreContentAdaptWithSize(false)
btnContinue:loadTextureNormal("common/common_btn_green2.png",0)
btnContinue:setTitleFontName("FZZhengHeiS-B-GB.ttf")
btnContinue:setTitleFontSize(50)
btnContinue:setTitleText("再玩一会")
btnContinue:setTitleColor({r = 229, g = 229, b = 229})
btnContinue:setScale9Enabled(true)
btnContinue:setCapInsets({x = 15, y = 11, width = 292, height = 91})
btnContinue:setLayoutComponentEnabled(true)
btnContinue:setName("btnContinue")
btnContinue:setTag(425)
btnContinue:setCascadeColorEnabled(true)
btnContinue:setCascadeOpacityEnabled(true)
btnContinue:setPosition(365.5474, -45.2327)
layout = ccui.LayoutComponent:bindLayoutComponent(btnContinue)
layout:setPositionPercentX(0.3287)
layout:setPositionPercentY(-0.1311)
layout:setPercentWidth(0.2896)
layout:setPercentHeight(0.3275)
layout:setSize({width = 322.0000, height = 113.0000})
layout:setLeftMargin(204.5474)
layout:setRightMargin(585.4526)
layout:setTopMargin(333.7327)
layout:setBottomMargin(-101.7327)
Image_1:addChild(btnContinue)

--Create btnExit
local btnExit = ccui.Button:create()
btnExit:ignoreContentAdaptWithSize(false)
btnExit:loadTextureNormal("common/common_btn_red.png",0)
btnExit:setTitleFontName("FZZhengHeiS-B-GB.ttf")
btnExit:setTitleFontSize(50)
btnExit:setTitleText("残忍离开")
btnExit:setTitleColor({r = 229, g = 229, b = 229})
btnExit:setScale9Enabled(true)
btnExit:setCapInsets({x = 15, y = 11, width = 278, height = 91})
btnExit:setLayoutComponentEnabled(true)
btnExit:setName("btnExit")
btnExit:setTag(426)
btnExit:setCascadeColorEnabled(true)
btnExit:setCascadeOpacityEnabled(true)
btnExit:setPosition(768.1476, -45.2327)
layout = ccui.LayoutComponent:bindLayoutComponent(btnExit)
layout:setPositionPercentX(0.6908)
layout:setPositionPercentY(-0.1311)
layout:setPercentWidth(0.2770)
layout:setPercentHeight(0.3275)
layout:setSize({width = 308.0000, height = 113.0000})
layout:setLeftMargin(614.1476)
layout:setRightMargin(189.8524)
layout:setTopMargin(333.7327)
layout:setBottomMargin(-101.7327)
Image_1:addChild(btnExit)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

