--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_1:loadTexture("menutiao.png",1)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(145)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setAnchorPoint(0.5000, 1.0000)
Image_1:setPosition(0.0000, -0.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setSize({width = 100.0000, height = 368.0000})
layout:setLeftMargin(-50.0000)
layout:setRightMargin(-50.0000)
layout:setTopMargin(0.0001)
layout:setBottomMargin(-368.0001)
Node:addChild(Image_1)

--Create set
local set = ccui.Button:create()
set:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
set:loadTextureNormal("reset.png",1)
set:setTitleFontSize(14)
set:setTitleColor({r = 65, g = 65, b = 70})
set:setScale9Enabled(true)
set:setCapInsets({x = 15, y = 11, width = 76, height = 95})
set:setLayoutComponentEnabled(true)
set:setName("set")
set:setTag(148)
set:setCascadeColorEnabled(true)
set:setCascadeOpacityEnabled(true)
set:setPosition(50.0000, 183.8086)
layout = ccui.LayoutComponent:bindLayoutComponent(set)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4995)
layout:setPercentWidth(1.0600)
layout:setPercentHeight(0.3179)
layout:setSize({width = 106.0000, height = 117.0000})
layout:setLeftMargin(-3.0000)
layout:setRightMargin(-3.0000)
layout:setTopMargin(125.6914)
layout:setBottomMargin(125.3086)
Image_1:addChild(set)

--Create exit
local exit = ccui.Button:create()
exit:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
exit:loadTextureNormal("exit.png",1)
exit:setTitleFontSize(14)
exit:setTitleColor({r = 65, g = 65, b = 70})
exit:setScale9Enabled(true)
exit:setCapInsets({x = 15, y = 11, width = 76, height = 95})
exit:setLayoutComponentEnabled(true)
exit:setName("exit")
exit:setTag(147)
exit:setCascadeColorEnabled(true)
exit:setCascadeOpacityEnabled(true)
exit:setPosition(50.0000, 67.4739)
layout = ccui.LayoutComponent:bindLayoutComponent(exit)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1834)
layout:setPercentWidth(1.0600)
layout:setPercentHeight(0.3179)
layout:setSize({width = 106.0000, height = 117.0000})
layout:setLeftMargin(-3.0000)
layout:setRightMargin(-3.0000)
layout:setTopMargin(242.0261)
layout:setBottomMargin(8.9739)
Image_1:addChild(exit)

--Create pull
local pull = ccui.Button:create()
pull:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
pull:loadTextureNormal("menu.png",1)
pull:setTitleFontSize(14)
pull:setTitleColor({r = 65, g = 65, b = 70})
pull:setScale9Enabled(true)
pull:setCapInsets({x = 15, y = 11, width = 76, height = 95})
pull:setLayoutComponentEnabled(true)
pull:setName("pull")
pull:setTag(146)
pull:setCascadeColorEnabled(true)
pull:setCascadeOpacityEnabled(true)
pull:setPosition(-1.0001, -55.8323)
layout = ccui.LayoutComponent:bindLayoutComponent(pull)
layout:setSize({width = 106.0000, height = 117.0000})
layout:setLeftMargin(-54.0001)
layout:setRightMargin(-51.9999)
layout:setTopMargin(-2.6677)
layout:setBottomMargin(-114.3323)
Node:addChild(pull)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

