--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create CalculationDi
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
local CalculationDi = cc.Sprite:createWithSpriteFrameName("CalculationDi.png")
CalculationDi:setName("CalculationDi")
CalculationDi:setTag(59)
CalculationDi:setCascadeColorEnabled(true)
CalculationDi:setCascadeOpacityEnabled(true)
CalculationDi:setPosition(-46.0001, -14.0004)
layout = ccui.LayoutComponent:bindLayoutComponent(CalculationDi)
layout:setSize({width = 674.0000, height = 135.0000})
layout:setLeftMargin(-383.0001)
layout:setRightMargin(-290.9999)
layout:setTopMargin(-53.4996)
layout:setBottomMargin(-81.5004)
CalculationDi:setBlendFunc({src = 1, dst = 771})
Node:addChild(CalculationDi)

--Create CalculationKuan_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
local CalculationKuan_1 = cc.Sprite:createWithSpriteFrameName("CalculationKuan.png")
CalculationKuan_1:setName("CalculationKuan_1")
CalculationKuan_1:setTag(60)
CalculationKuan_1:setCascadeColorEnabled(true)
CalculationKuan_1:setCascadeOpacityEnabled(true)
CalculationKuan_1:setPosition(-278.0004, -14.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(CalculationKuan_1)
layout:setSize({width = 90.0000, height = 90.0000})
layout:setLeftMargin(-323.0004)
layout:setRightMargin(233.0004)
layout:setTopMargin(-30.9998)
layout:setBottomMargin(-59.0002)
CalculationKuan_1:setBlendFunc({src = 1, dst = 771})
Node:addChild(CalculationKuan_1)

--Create shu
local shu = ccui.TextAtlas:create([[]],
													"bullfighting/wenzishu4.png",
													40,
													53,
													"0")
shu:setLayoutComponentEnabled(true)
shu:setName("shu")
shu:setTag(64)
shu:setCascadeColorEnabled(true)
shu:setCascadeOpacityEnabled(true)
shu:setPosition(45.0000, 41.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(shu)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4556)
layout:setLeftMargin(45.0000)
layout:setRightMargin(45.0000)
layout:setTopMargin(49.0000)
layout:setBottomMargin(41.0000)
CalculationKuan_1:addChild(shu)

--Create CalculationKuan_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
local CalculationKuan_2 = cc.Sprite:createWithSpriteFrameName("CalculationKuan.png")
CalculationKuan_2:setName("CalculationKuan_2")
CalculationKuan_2:setTag(61)
CalculationKuan_2:setCascadeColorEnabled(true)
CalculationKuan_2:setCascadeOpacityEnabled(true)
CalculationKuan_2:setPosition(-129.1509, -14.0003)
layout = ccui.LayoutComponent:bindLayoutComponent(CalculationKuan_2)
layout:setSize({width = 90.0000, height = 90.0000})
layout:setLeftMargin(-174.1509)
layout:setRightMargin(84.1509)
layout:setTopMargin(-30.9997)
layout:setBottomMargin(-59.0003)
CalculationKuan_2:setBlendFunc({src = 1, dst = 771})
Node:addChild(CalculationKuan_2)

--Create shu
local shu = ccui.TextAtlas:create([[]],
													"bullfighting/wenzishu4.png",
													40,
													53,
													"0")
shu:setLayoutComponentEnabled(true)
shu:setName("shu")
shu:setTag(65)
shu:setCascadeColorEnabled(true)
shu:setCascadeOpacityEnabled(true)
shu:setPosition(45.0000, 41.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(shu)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4556)
layout:setLeftMargin(45.0000)
layout:setRightMargin(45.0000)
layout:setTopMargin(49.0000)
layout:setBottomMargin(41.0000)
CalculationKuan_2:addChild(shu)

--Create CalculationKuan_3
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
local CalculationKuan_3 = cc.Sprite:createWithSpriteFrameName("CalculationKuan.png")
CalculationKuan_3:setName("CalculationKuan_3")
CalculationKuan_3:setTag(62)
CalculationKuan_3:setCascadeColorEnabled(true)
CalculationKuan_3:setCascadeOpacityEnabled(true)
CalculationKuan_3:setPosition(21.1501, -14.0003)
layout = ccui.LayoutComponent:bindLayoutComponent(CalculationKuan_3)
layout:setSize({width = 90.0000, height = 90.0000})
layout:setLeftMargin(-23.8499)
layout:setRightMargin(-66.1501)
layout:setTopMargin(-30.9997)
layout:setBottomMargin(-59.0003)
CalculationKuan_3:setBlendFunc({src = 1, dst = 771})
Node:addChild(CalculationKuan_3)

--Create shu
local shu = ccui.TextAtlas:create([[]],
													"bullfighting/wenzishu4.png",
													40,
													53,
													"0")
shu:setLayoutComponentEnabled(true)
shu:setName("shu")
shu:setTag(66)
shu:setCascadeColorEnabled(true)
shu:setCascadeOpacityEnabled(true)
shu:setPosition(45.0000, 41.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(shu)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4556)
layout:setLeftMargin(45.0000)
layout:setRightMargin(45.0000)
layout:setTopMargin(49.0000)
layout:setBottomMargin(41.0000)
CalculationKuan_3:addChild(shu)

--Create CalculationKuan_4
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
local CalculationKuan_4 = cc.Sprite:createWithSpriteFrameName("CalculationKuan.png")
CalculationKuan_4:setName("CalculationKuan_4")
CalculationKuan_4:setTag(63)
CalculationKuan_4:setCascadeColorEnabled(true)
CalculationKuan_4:setCascadeOpacityEnabled(true)
CalculationKuan_4:setPosition(175.7774, -14.0003)
layout = ccui.LayoutComponent:bindLayoutComponent(CalculationKuan_4)
layout:setSize({width = 90.0000, height = 90.0000})
layout:setLeftMargin(130.7774)
layout:setRightMargin(-220.7774)
layout:setTopMargin(-30.9997)
layout:setBottomMargin(-59.0003)
CalculationKuan_4:setBlendFunc({src = 1, dst = 771})
Node:addChild(CalculationKuan_4)

--Create shu
local shu = ccui.TextAtlas:create([[]],
													"bullfighting/wenzishu4.png",
													40,
													53,
													"0")
shu:setLayoutComponentEnabled(true)
shu:setName("shu")
shu:setTag(67)
shu:setCascadeColorEnabled(true)
shu:setCascadeOpacityEnabled(true)
shu:setPosition(45.0000, 41.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(shu)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4556)
layout:setLeftMargin(45.0000)
layout:setRightMargin(45.0000)
layout:setTopMargin(49.0000)
layout:setBottomMargin(41.0000)
CalculationKuan_4:addChild(shu)

--Create Buttontip
local Buttontip = ccui.Button:create()
Buttontip:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Buttontip:loadTextureNormal("light.png",1)
Buttontip:setTitleFontSize(14)
Buttontip:setTitleColor({r = 65, g = 65, b = 70})
Buttontip:setScale9Enabled(true)
Buttontip:setCapInsets({x = 15, y = 11, width = 67, height = 83})
Buttontip:setLayoutComponentEnabled(true)
Buttontip:setName("Buttontip")
Buttontip:setTag(68)
Buttontip:setCascadeColorEnabled(true)
Buttontip:setCascadeOpacityEnabled(true)
Buttontip:setPosition(346.6949, -19.4462)
layout = ccui.LayoutComponent:bindLayoutComponent(Buttontip)
layout:setSize({width = 97.0000, height = 105.0000})
layout:setLeftMargin(298.1949)
layout:setRightMargin(-395.1949)
layout:setTopMargin(-33.0538)
layout:setBottomMargin(-71.9462)
Node:addChild(Buttontip)

--Create tipsPao
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
local tipsPao = cc.Sprite:createWithSpriteFrameName("tipsPao.png")
tipsPao:setName("tipsPao")
tipsPao:setTag(71)
tipsPao:setCascadeColorEnabled(true)
tipsPao:setCascadeOpacityEnabled(true)
tipsPao:setPosition(228.0887, 87.0138)
layout = ccui.LayoutComponent:bindLayoutComponent(tipsPao)
layout:setSize({width = 333.0000, height = 107.0000})
layout:setLeftMargin(61.5887)
layout:setRightMargin(-394.5887)
layout:setTopMargin(-140.5138)
layout:setBottomMargin(33.5138)
tipsPao:setBlendFunc({src = 1, dst = 771})
Node:addChild(tipsPao)

--Create Text_
local Text_ = ccui.Text:create()
Text_:ignoreContentAdaptWithSize(false)
Text_:setFontName("FZZhengHeiS-B-GB.ttf")
Text_:setFontSize(22)
Text_:setString([[算不出牌记得点我！50金币/次（超时系统自动使用）]])
Text_:setLayoutComponentEnabled(true)
Text_:setName("Text_")
Text_:setTag(72)
Text_:setCascadeColorEnabled(true)
Text_:setCascadeOpacityEnabled(true)
Text_:setPosition(167.3767, 60.8379)
Text_:setTextColor({r = 245, g = 253, b = 255})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_)
layout:setPositionPercentX(0.5026)
layout:setPositionPercentY(0.5686)
layout:setPercentWidth(0.9009)
layout:setPercentHeight(0.5607)
layout:setSize({width = 300.0000, height = 60.0000})
layout:setLeftMargin(17.3767)
layout:setRightMargin(15.6233)
layout:setTopMargin(16.1621)
layout:setBottomMargin(30.8379)
tipsPao:addChild(Text_)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

