--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_kuang:loadTexture("headshukuang.png",1)
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(23)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setSize({width = 180.0000, height = 248.0000})
layout:setLeftMargin(-90.0000)
layout:setRightMargin(-90.0000)
layout:setTopMargin(-124.0000)
layout:setBottomMargin(-124.0000)
Node:addChild(Image_kuang)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_bg:loadTexture("headshu.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(260)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 178.0000, height = 244.0000})
layout:setLeftMargin(-89.0000)
layout:setRightMargin(-89.0000)
layout:setTopMargin(-122.0000)
layout:setBottomMargin(-122.0000)
Node:addChild(Image_bg)

--Create Image_headbg
local Image_headbg = ccui.ImageView:create()
Image_headbg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_headbg:loadTexture("otherkuang.png",1)
Image_headbg:setTouchEnabled(true);
Image_headbg:setLayoutComponentEnabled(true)
Image_headbg:setName("Image_headbg")
Image_headbg:setTag(261)
Image_headbg:setCascadeColorEnabled(true)
Image_headbg:setCascadeOpacityEnabled(true)
Image_headbg:setPosition(88.6663, 172.8427)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_headbg)
layout:setPositionPercentX(0.4981)
layout:setPositionPercentY(0.7084)
layout:setPercentWidth(0.6798)
layout:setPercentHeight(0.4959)
layout:setSize({width = 121.0000, height = 121.0000})
layout:setLeftMargin(28.1663)
layout:setRightMargin(28.8337)
layout:setTopMargin(10.6573)
layout:setBottomMargin(112.3427)
Image_bg:addChild(Image_headbg)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("")
Text_name:setFontSize(28)
Text_name:setString([[userName]])
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(264)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(88.4356, 88.0989)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.4968)
layout:setPositionPercentY(0.3611)
layout:setPercentWidth(0.6292)
layout:setPercentHeight(0.1148)
layout:setSize({width = 112.0000, height = 28.0000})
layout:setLeftMargin(32.4356)
layout:setRightMargin(33.5644)
layout:setTopMargin(141.9011)
layout:setBottomMargin(74.0989)
Image_bg:addChild(Text_name)

--Create Image_gold
local Image_gold = ccui.ImageView:create()
Image_gold:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_gold:loadTexture("goldtiao2.png",1)
Image_gold:setScale9Enabled(true)
Image_gold:setCapInsets({x = 59, y = 15, width = 32, height = 26})
Image_gold:setLayoutComponentEnabled(true)
Image_gold:setName("Image_gold")
Image_gold:setTag(265)
Image_gold:setCascadeColorEnabled(true)
Image_gold:setCascadeOpacityEnabled(true)
Image_gold:setPosition(89.7732, 41.4365)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_gold)
layout:setPositionPercentX(0.5043)
layout:setPositionPercentY(0.1698)
layout:setPercentWidth(0.9326)
layout:setPercentHeight(0.2418)
layout:setSize({width = 166.0000, height = 59.0000})
layout:setLeftMargin(6.7732)
layout:setRightMargin(5.2268)
layout:setTopMargin(173.0635)
layout:setBottomMargin(11.9365)
Image_bg:addChild(Image_gold)

--Create Text_gold
local Text_gold = ccui.Text:create()
Text_gold:ignoreContentAdaptWithSize(true)
Text_gold:setTextAreaSize({width = 0, height = 0})
Text_gold:setFontName("FZZhengHeiS-B-GB.ttf")
Text_gold:setFontSize(22)
Text_gold:setString([[000,000]])
Text_gold:setLayoutComponentEnabled(true)
Text_gold:setName("Text_gold")
Text_gold:setTag(266)
Text_gold:setCascadeColorEnabled(true)
Text_gold:setCascadeOpacityEnabled(true)
Text_gold:setPosition(100.4008, 27.9763)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_gold)
layout:setPositionPercentX(0.6048)
layout:setPositionPercentY(0.4742)
layout:setPercentWidth(0.5301)
layout:setPercentHeight(0.4407)
layout:setSize({width = 88.0000, height = 26.0000})
layout:setLeftMargin(56.4008)
layout:setRightMargin(21.5992)
layout:setTopMargin(18.0237)
layout:setBottomMargin(14.9763)
Image_gold:addChild(Text_gold)

--Create beiandget
local beiandget = ccui.TextAtlas:create([[00]],
													"bullfighting/wenzishu2.png",
													56,
													55,
													"0")
beiandget:setLayoutComponentEnabled(true)
beiandget:setName("beiandget")
beiandget:setTag(99)
beiandget:setCascadeColorEnabled(true)
beiandget:setCascadeOpacityEnabled(true)
beiandget:setPosition(0.9285, -187.0045)
layout = ccui.LayoutComponent:bindLayoutComponent(beiandget)
layout:setSize({width = 112.0000, height = 55.0000})
layout:setLeftMargin(-55.0715)
layout:setRightMargin(-56.9285)
layout:setTopMargin(159.5045)
layout:setBottomMargin(-214.5045)
Node:addChild(beiandget)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(0.4167)
--Create Animation List

result['root'] = Node
return result;
end

return Result

