--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_kuang:loadTexture("headhengkuang.png",1)
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(36)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setPosition(-0.2061, 1.4529)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setSize({width = 326.0000, height = 142.0000})
layout:setLeftMargin(-163.2061)
layout:setRightMargin(-162.7939)
layout:setTopMargin(-72.4529)
layout:setBottomMargin(-69.5471)
Node:addChild(Image_kuang)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_bg:loadTexture("headheng.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(212)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(-0.3738, 0.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 321.0000, height = 139.0000})
layout:setLeftMargin(-160.8738)
layout:setRightMargin(-160.1262)
layout:setTopMargin(-69.5002)
layout:setBottomMargin(-69.4998)
Node:addChild(Image_bg)

--Create Image_headbg
local Image_headbg = ccui.ImageView:create()
Image_headbg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_headbg:loadTexture("otherkuang.png",1)
Image_headbg:setTouchEnabled(true);
Image_headbg:setLayoutComponentEnabled(true)
Image_headbg:setName("Image_headbg")
Image_headbg:setTag(213)
Image_headbg:setCascadeColorEnabled(true)
Image_headbg:setCascadeOpacityEnabled(true)
Image_headbg:setPosition(71.7887, 69.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_headbg)
layout:setPositionPercentX(0.2236)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3769)
layout:setPercentHeight(0.8705)
layout:setSize({width = 121.0000, height = 121.0000})
layout:setLeftMargin(11.2887)
layout:setRightMargin(188.7113)
layout:setTopMargin(9.0000)
layout:setBottomMargin(9.0000)
Image_bg:addChild(Image_headbg)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("")
Text_name:setFontSize(28)
Text_name:setString([[userNameuse]])
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(254)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(221.8300, 87.4900)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.6911)
layout:setPositionPercentY(0.6294)
layout:setPercentWidth(0.4798)
layout:setPercentHeight(0.2014)
layout:setSize({width = 154.0000, height = 28.0000})
layout:setLeftMargin(144.8300)
layout:setRightMargin(22.1700)
layout:setTopMargin(37.5100)
layout:setBottomMargin(73.4900)
Image_bg:addChild(Text_name)

--Create Image_gold
local Image_gold = ccui.ImageView:create()
Image_gold:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_gold:loadTexture("goldtiao2.png",1)
Image_gold:setScale9Enabled(true)
Image_gold:setCapInsets({x = 59, y = 15, width = 32, height = 26})
Image_gold:setLayoutComponentEnabled(true)
Image_gold:setName("Image_gold")
Image_gold:setTag(255)
Image_gold:setCascadeColorEnabled(true)
Image_gold:setCascadeOpacityEnabled(true)
Image_gold:setPosition(226.1624, 34.1300)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_gold)
layout:setPositionPercentX(0.7046)
layout:setPositionPercentY(0.2455)
layout:setPercentWidth(0.5171)
layout:setPercentHeight(0.4245)
layout:setSize({width = 166.0000, height = 59.0000})
layout:setLeftMargin(143.1624)
layout:setRightMargin(11.8376)
layout:setTopMargin(75.3700)
layout:setBottomMargin(4.6300)
Image_bg:addChild(Image_gold)

--Create Text_gold
local Text_gold = ccui.Text:create()
Text_gold:ignoreContentAdaptWithSize(true)
Text_gold:setTextAreaSize({width = 0, height = 0})
Text_gold:setFontName("FZZhengHeiS-B-GB.ttf")
Text_gold:setFontSize(22)
Text_gold:setString([[000,000]])
Text_gold:setLayoutComponentEnabled(true)
Text_gold:setName("Text_gold")
Text_gold:setTag(256)
Text_gold:setCascadeColorEnabled(true)
Text_gold:setCascadeOpacityEnabled(true)
Text_gold:setPosition(100.4008, 27.9763)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_gold)
layout:setPositionPercentX(0.6048)
layout:setPositionPercentY(0.4742)
layout:setPercentWidth(0.5301)
layout:setPercentHeight(0.4407)
layout:setSize({width = 88.0000, height = 26.0000})
layout:setLeftMargin(56.4008)
layout:setRightMargin(21.5992)
layout:setTopMargin(18.0237)
layout:setBottomMargin(14.9763)
Image_gold:addChild(Text_gold)

--Create beiandget
local beiandget = ccui.TextAtlas:create([[90]],
													"bullfighting/wenzishu2.png",
													56,
													55,
													"0")
beiandget:setLayoutComponentEnabled(true)
beiandget:setName("beiandget")
beiandget:setTag(91)
beiandget:setCascadeColorEnabled(true)
beiandget:setCascadeOpacityEnabled(true)
beiandget:setPosition(256.3938, 1.7206)
layout = ccui.LayoutComponent:bindLayoutComponent(beiandget)
layout:setSize({width = 112.0000, height = 55.0000})
layout:setLeftMargin(200.3938)
layout:setRightMargin(-312.3938)
layout:setTopMargin(-29.2206)
layout:setBottomMargin(-25.7794)
Node:addChild(beiandget)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(0.4167)
--Create Animation List

result['root'] = Node
return result;
end

return Result

