--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_bg:loadTexture("buttomkuang.png",1)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(68)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 1920.0000, height = 102.0000})
layout:setLeftMargin(-960.0000)
layout:setRightMargin(-960.0000)
layout:setTopMargin(-51.0000)
layout:setBottomMargin(-51.0000)
Node:addChild(Image_bg)

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_kuang:loadTexture("headhengkuang.png",1)
Image_kuang:setScale9Enabled(true)
Image_kuang:setCapInsets({x = 100, y = 50, width = 124, height = 40})
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(35)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setPosition(106.5306, 73.0769)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setPositionPercentX(0.0555)
layout:setPositionPercentY(0.7164)
layout:setPercentWidth(0.0651)
layout:setPercentHeight(1.2255)
layout:setSize({width = 125.0000, height = 125.0000})
layout:setLeftMargin(44.0306)
layout:setRightMargin(1750.9690)
layout:setTopMargin(-33.5769)
layout:setBottomMargin(10.5769)
Image_bg:addChild(Image_kuang)

--Create Image_headbg
local Image_headbg = ccui.ImageView:create()
Image_headbg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_headbg:loadTexture("ourkuang.png",1)
Image_headbg:setTouchEnabled(true);
Image_headbg:setLayoutComponentEnabled(true)
Image_headbg:setName("Image_headbg")
Image_headbg:setTag(69)
Image_headbg:setCascadeColorEnabled(true)
Image_headbg:setCascadeOpacityEnabled(true)
Image_headbg:setPosition(106.7325, 72.5100)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_headbg)
layout:setPositionPercentX(0.0556)
layout:setPositionPercentY(0.7109)
layout:setPercentWidth(0.0630)
layout:setPercentHeight(1.1863)
layout:setSize({width = 121.0000, height = 121.0000})
layout:setLeftMargin(46.2325)
layout:setRightMargin(1752.7670)
layout:setTopMargin(-31.0100)
layout:setBottomMargin(12.0100)
Image_bg:addChild(Image_headbg)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("")
Text_name:setFontSize(32)
Text_name:setString([[userName]])
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(70)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(0.0000, 0.5000)
Text_name:setPosition(153.0036, 35.9661)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(1.2645)
layout:setPositionPercentY(0.2972)
layout:setPercentWidth(1.0579)
layout:setPercentHeight(0.2727)
layout:setSize({width = 128.0000, height = 33.0000})
layout:setLeftMargin(153.0036)
layout:setRightMargin(-160.0036)
layout:setTopMargin(68.5339)
layout:setBottomMargin(19.4661)
Image_headbg:addChild(Text_name)

--Create beiandget
local beiandget = ccui.ImageView:create()
beiandget:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
beiandget:loadTexture("headshukuang.png",1)
beiandget:setLayoutComponentEnabled(true)
beiandget:setName("beiandget")
beiandget:setTag(42)
beiandget:setCascadeColorEnabled(true)
beiandget:setCascadeOpacityEnabled(true)
beiandget:setVisible(false)
beiandget:setPosition(60.1326, 61.1317)
layout = ccui.LayoutComponent:bindLayoutComponent(beiandget)
layout:setPositionPercentX(0.4970)
layout:setPositionPercentY(0.5052)
layout:setPercentWidth(1.0165)
layout:setPercentHeight(1.0165)
layout:setSize({width = 123.0000, height = 123.0000})
layout:setLeftMargin(-1.3674)
layout:setRightMargin(-0.6326)
layout:setTopMargin(-1.6317)
layout:setBottomMargin(-0.3683)
Image_headbg:addChild(beiandget)

--Create Image_gold
local Image_gold = ccui.ImageView:create()
Image_gold:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Image_gold:loadTexture("goldtiao.png",1)
Image_gold:setLayoutComponentEnabled(true)
Image_gold:setName("Image_gold")
Image_gold:setTag(71)
Image_gold:setCascadeColorEnabled(true)
Image_gold:setCascadeOpacityEnabled(true)
Image_gold:setPosition(582.7324, 47.0000)
Image_gold:setScaleX(1.2000)
Image_gold:setScaleY(1.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_gold)
layout:setPositionPercentX(0.3035)
layout:setPositionPercentY(0.4608)
layout:setPercentWidth(0.1396)
layout:setPercentHeight(0.5490)
layout:setSize({width = 268.0000, height = 56.0000})
layout:setLeftMargin(448.7324)
layout:setRightMargin(1203.2680)
layout:setTopMargin(27.0000)
layout:setBottomMargin(19.0000)
Image_bg:addChild(Image_gold)

--Create Text_gold
local Text_gold = ccui.Text:create()
Text_gold:ignoreContentAdaptWithSize(true)
Text_gold:setTextAreaSize({width = 0, height = 0})
Text_gold:setFontName("FZZhengHeiS-B-GB.ttf")
Text_gold:setFontSize(30)
Text_gold:setString([[0]])
Text_gold:setLayoutComponentEnabled(true)
Text_gold:setName("Text_gold")
Text_gold:setTag(72)
Text_gold:setCascadeColorEnabled(true)
Text_gold:setCascadeOpacityEnabled(true)
Text_gold:setPosition(135.5932, 25.8405)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_gold)
layout:setPositionPercentX(0.5059)
layout:setPositionPercentY(0.4614)
layout:setPercentWidth(0.0746)
layout:setPercentHeight(0.6250)
layout:setSize({width = 20.0000, height = 35.0000})
layout:setLeftMargin(125.5932)
layout:setRightMargin(122.4068)
layout:setTopMargin(12.6595)
layout:setBottomMargin(8.3405)
Image_gold:addChild(Text_gold)

--Create Button_add
local Button_add = ccui.Button:create()
Button_add:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
Button_add:loadTextureNormal("btnbuy.png",1)
Button_add:setTitleFontSize(14)
Button_add:setTitleColor({r = 65, g = 65, b = 70})
Button_add:setScale9Enabled(true)
Button_add:setCapInsets({x = 15, y = 11, width = 58, height = 61})
Button_add:setLayoutComponentEnabled(true)
Button_add:setName("Button_add")
Button_add:setTag(73)
Button_add:setCascadeColorEnabled(true)
Button_add:setCascadeOpacityEnabled(true)
Button_add:setPosition(259.4489, 28.9050)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_add)
layout:setPositionPercentX(0.9681)
layout:setPositionPercentY(0.5162)
layout:setPercentWidth(0.3284)
layout:setPercentHeight(1.4821)
layout:setSize({width = 88.0000, height = 83.0000})
layout:setLeftMargin(215.4489)
layout:setRightMargin(-35.4489)
layout:setTopMargin(-14.4050)
layout:setBottomMargin(-12.5950)
Image_gold:addChild(Button_add)

--Create shop
local shop = ccui.Button:create()
shop:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
shop:loadTextureNormal("btnShop.png",1)
shop:setTitleFontSize(14)
shop:setTitleColor({r = 65, g = 65, b = 70})
shop:setScale9Enabled(true)
shop:setCapInsets({x = 15, y = 11, width = 226, height = 60})
shop:setLayoutComponentEnabled(true)
shop:setName("shop")
shop:setTag(246)
shop:setCascadeColorEnabled(true)
shop:setCascadeOpacityEnabled(true)
shop:setPosition(86.0162, -4.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(shop)
layout:setSize({width = 256.0000, height = 82.0000})
layout:setLeftMargin(-41.9838)
layout:setRightMargin(-214.0162)
layout:setTopMargin(-37.0000)
layout:setBottomMargin(-45.0000)
Node:addChild(shop)

--Create changeCard
local changeCard = ccui.Button:create()
changeCard:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
changeCard:loadTextureNormal("btnChange.png",1)
changeCard:setTitleFontSize(14)
changeCard:setTitleColor({r = 65, g = 65, b = 70})
changeCard:setScale9Enabled(true)
changeCard:setCapInsets({x = 15, y = 11, width = 229, height = 60})
changeCard:setLayoutComponentEnabled(true)
changeCard:setName("changeCard")
changeCard:setTag(247)
changeCard:setCascadeColorEnabled(true)
changeCard:setCascadeOpacityEnabled(true)
changeCard:setVisible(false)
changeCard:setPosition(384.0299, -4.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(changeCard)
layout:setSize({width = 259.0000, height = 82.0000})
layout:setLeftMargin(254.5299)
layout:setRightMargin(-513.5299)
layout:setTopMargin(-37.0000)
layout:setBottomMargin(-45.0000)
Node:addChild(changeCard)

--Create dian
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
local dian = cc.Sprite:createWithSpriteFrameName("dian.png")
dian:setName("dian")
dian:setTag(249)
dian:setCascadeColorEnabled(true)
dian:setCascadeOpacityEnabled(true)
dian:setPosition(240.2041, 68.0551)
layout = ccui.LayoutComponent:bindLayoutComponent(dian)
layout:setPositionPercentX(0.9274)
layout:setPositionPercentY(0.8299)
layout:setPercentWidth(0.3127)
layout:setPercentHeight(1.0000)
layout:setSize({width = 81.0000, height = 82.0000})
layout:setLeftMargin(199.7041)
layout:setRightMargin(-21.7041)
layout:setTopMargin(-27.0551)
layout:setBottomMargin(27.0551)
dian:setBlendFunc({src = 1, dst = 771})
changeCard:addChild(dian)

--Create count
local count = ccui.Text:create()
count:ignoreContentAdaptWithSize(true)
count:setTextAreaSize({width = 0, height = 0})
count:setFontName("FZZhengHeiS-B-GB.ttf")
count:setFontSize(30)
count:setString([[9]])
count:setLayoutComponentEnabled(true)
count:setName("count")
count:setTag(250)
count:setCascadeColorEnabled(true)
count:setCascadeOpacityEnabled(true)
count:setPosition(39.5327, 40.7399)
layout = ccui.LayoutComponent:bindLayoutComponent(count)
layout:setPositionPercentX(0.4881)
layout:setPositionPercentY(0.4968)
layout:setPercentWidth(0.2469)
layout:setPercentHeight(0.4268)
layout:setSize({width = 20.0000, height = 35.0000})
layout:setLeftMargin(29.5327)
layout:setRightMargin(31.4673)
layout:setTopMargin(23.7601)
layout:setBottomMargin(23.2399)
dian:addChild(count)

--Create chat
local chat = ccui.Button:create()
chat:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
chat:loadTextureNormal("btnchat.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
chat:loadTextureDisabled("btnchat2.png",1)
chat:setTitleFontSize(14)
chat:setTitleColor({r = 65, g = 65, b = 70})
chat:setScale9Enabled(true)
chat:setCapInsets({x = 15, y = 11, width = 172, height = 59})
chat:setLayoutComponentEnabled(true)
chat:setName("chat")
chat:setTag(248)
chat:setCascadeColorEnabled(true)
chat:setCascadeOpacityEnabled(true)
chat:setPosition(852.7937, -4.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(chat)
layout:setSize({width = 202.0000, height = 81.0000})
layout:setLeftMargin(751.7937)
layout:setRightMargin(-953.7937)
layout:setTopMargin(-36.5000)
layout:setBottomMargin(-44.5000)
Node:addChild(chat)

--Create beiandget
local beiandget = ccui.TextAtlas:create([[90]],
													"bullfighting/wenzishu2.png",
													56,
													55,
													"0")
beiandget:setLayoutComponentEnabled(true)
beiandget:setName("beiandget")
beiandget:setTag(46)
beiandget:setCascadeColorEnabled(true)
beiandget:setCascadeOpacityEnabled(true)
beiandget:setPosition(-851.4716, 118.2083)
layout = ccui.LayoutComponent:bindLayoutComponent(beiandget)
layout:setSize({width = 112.0000, height = 55.0000})
layout:setLeftMargin(-907.4716)
layout:setRightMargin(795.4716)
layout:setTopMargin(-145.7083)
layout:setBottomMargin(90.7083)
Node:addChild(beiandget)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(0.4167)
--Create Animation List
local animation0 = {name="animation0", startIndex=0, endIndex=0}
result['animation']:addAnimationInfo(animation0)
local animation1 = {name="animation1", startIndex=0, endIndex=5}
result['animation']:addAnimationInfo(animation1)

result['root'] = Node
return result;
end

return Result

