--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create Image_bg_house
local Image_bg_house = ccui.ImageView:create()
Image_bg_house:ignoreContentAdaptWithSize(false)
Image_bg_house:loadTexture("bullfighting/background.jpg",0)
Image_bg_house:setLayoutComponentEnabled(true)
Image_bg_house:setName("Image_bg_house")
Image_bg_house:setTag(130)
Image_bg_house:setCascadeColorEnabled(true)
Image_bg_house:setCascadeOpacityEnabled(true)
Image_bg_house:setPosition(960.0000, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg_house)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1920.0000, height = 1080.0000})
Layer:addChild(Image_bg_house)

--Create Image_bg_desk
local Image_bg_desk = ccui.ImageView:create()
Image_bg_desk:ignoreContentAdaptWithSize(false)
Image_bg_desk:loadTexture("bullfighting/desk.png",0)
Image_bg_desk:setScale9Enabled(true)
Image_bg_desk:setCapInsets({x = 633, y = 237, width = 654, height = 245})
Image_bg_desk:setLayoutComponentEnabled(true)
Image_bg_desk:setName("Image_bg_desk")
Image_bg_desk:setTag(131)
Image_bg_desk:setCascadeColorEnabled(true)
Image_bg_desk:setCascadeOpacityEnabled(true)
Image_bg_desk:setPosition(960.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg_desk)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3333)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.6657)
layout:setSize({width = 1920.0000, height = 719.0000})
layout:setVerticalEdge(1)
layout:setTopMargin(360.5000)
layout:setBottomMargin(0.5000)
Layer:addChild(Image_bg_desk)

--Create littlekuang
local littlekuang = ccui.ImageView:create()
littlekuang:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("bullfighting/others.plist")
littlekuang:loadTexture("littlekuang.png",1)
littlekuang:setLayoutComponentEnabled(true)
littlekuang:setName("littlekuang")
littlekuang:setTag(7)
littlekuang:setCascadeColorEnabled(true)
littlekuang:setCascadeOpacityEnabled(true)
littlekuang:setPosition(150.9279, 1030.8590)
layout = ccui.LayoutComponent:bindLayoutComponent(littlekuang)
layout:setPositionPercentX(0.0786)
layout:setPositionPercentY(0.9545)
layout:setPercentWidth(0.1448)
layout:setPercentHeight(0.0769)
layout:setSize({width = 278.0000, height = 83.0000})
layout:setLeftMargin(11.9279)
layout:setRightMargin(1630.0720)
layout:setTopMargin(7.6409)
layout:setBottomMargin(989.3591)
Layer:addChild(littlekuang)

--Create Text_5
local Text_5 = ccui.Text:create()
Text_5:ignoreContentAdaptWithSize(true)
Text_5:setTextAreaSize({width = 0, height = 0})
Text_5:setFontName("FZZhengHeiS-B-GB.ttf")
Text_5:setFontSize(40)
Text_5:setString([[底分:]])
Text_5:setLayoutComponentEnabled(true)
Text_5:setName("Text_5")
Text_5:setTag(38)
Text_5:setCascadeColorEnabled(true)
Text_5:setCascadeOpacityEnabled(true)
Text_5:setPosition(89.7888, 41.2145)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_5)
layout:setPositionPercentX(0.3230)
layout:setPositionPercentY(0.4966)
layout:setPercentWidth(0.3345)
layout:setPercentHeight(0.5542)
layout:setSize({width = 93.0000, height = 46.0000})
layout:setLeftMargin(43.2888)
layout:setRightMargin(141.7112)
layout:setTopMargin(18.7856)
layout:setBottomMargin(18.2145)
littlekuang:addChild(Text_5)

--Create count
local count = ccui.Text:create()
count:ignoreContentAdaptWithSize(true)
count:setTextAreaSize({width = 0, height = 0})
count:setFontName("FZZhengHeiS-B-GB.ttf")
count:setFontSize(30)
count:setString([[1000]])
count:setLayoutComponentEnabled(true)
count:setName("count")
count:setTag(39)
count:setCascadeColorEnabled(true)
count:setCascadeOpacityEnabled(true)
count:setPosition(177.6428, 37.7015)
count:setTextColor({r = 255, g = 165, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(count)
layout:setPositionPercentX(0.6390)
layout:setPositionPercentY(0.4542)
layout:setPercentWidth(0.2662)
layout:setPercentHeight(0.4217)
layout:setSize({width = 74.0000, height = 35.0000})
layout:setLeftMargin(140.6428)
layout:setRightMargin(63.3572)
layout:setTopMargin(27.7985)
layout:setBottomMargin(20.2015)
littlekuang:addChild(count)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

