--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/store/store_plist.plist")
Image_bg:loadTexture("store_prop_item_bg.png",1)
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(67)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 304.0000, height = 330.0000})
layout:setLeftMargin(-152.0000)
layout:setRightMargin(-152.0000)
layout:setTopMargin(-165.0000)
layout:setBottomMargin(-165.0000)
Node:addChild(Image_bg)

--Create Image_icon
local Image_icon = ccui.ImageView:create()
Image_icon:ignoreContentAdaptWithSize(false)
Image_icon:loadTexture("Default/ImageFile.png",0)
Image_icon:setLayoutComponentEnabled(true)
Image_icon:setName("Image_icon")
Image_icon:setTag(401)
Image_icon:setCascadeColorEnabled(true)
Image_icon:setCascadeOpacityEnabled(true)
Image_icon:setPosition(152.0070, 223.2885)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_icon)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6766)
layout:setPercentWidth(0.5921)
layout:setPercentHeight(0.5455)
layout:setSize({width = 180.0000, height = 180.0000})
layout:setLeftMargin(62.0070)
layout:setRightMargin(61.9930)
layout:setTopMargin(16.7115)
layout:setBottomMargin(133.2885)
Image_bg:addChild(Image_icon)

--Create Image_desc
local Image_desc = ccui.ImageView:create()
Image_desc:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/store/store_plist.plist")
Image_desc:loadTexture("store_prop_desc_mask.png",1)
Image_desc:setLayoutComponentEnabled(true)
Image_desc:setName("Image_desc")
Image_desc:setTag(402)
Image_desc:setCascadeColorEnabled(true)
Image_desc:setCascadeOpacityEnabled(true)
Image_desc:setPosition(151.7943, 145.5666)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_desc)
layout:setPositionPercentX(0.4993)
layout:setPositionPercentY(0.4411)
layout:setPercentWidth(0.8914)
layout:setPercentHeight(0.1424)
layout:setSize({width = 271.0000, height = 47.0000})
layout:setLeftMargin(16.2943)
layout:setRightMargin(16.7057)
layout:setTopMargin(160.9334)
layout:setBottomMargin(122.0666)
Image_bg:addChild(Image_desc)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(true)
Text_desc:setTextAreaSize({width = 0, height = 0})
Text_desc:setFontName("FZZhengHeiS-B-GB.ttf")
Text_desc:setFontSize(26)
Text_desc:setString([[点击切换商品数量]])
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(403)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setPosition(136.0339, 21.2177)
Text_desc:setTextColor({r = 232, g = 241, b = 214})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.5020)
layout:setPositionPercentY(0.4514)
layout:setPercentWidth(0.7749)
layout:setPercentHeight(0.6809)
layout:setSize({width = 210.0000, height = 32.0000})
layout:setLeftMargin(31.0339)
layout:setRightMargin(29.9661)
layout:setTopMargin(9.7823)
layout:setBottomMargin(5.2177)
Image_desc:addChild(Text_desc)

--Create Text_content
local Text_content = ccui.Text:create()
Text_content:ignoreContentAdaptWithSize(true)
Text_content:setTextAreaSize({width = 0, height = 0})
Text_content:setFontName("FZZhengHeiS-B-GB.ttf")
Text_content:setFontSize(32)
Text_content:setString([[玫瑰花x14]])
Text_content:setLayoutComponentEnabled(true)
Text_content:setName("Text_content")
Text_content:setTag(404)
Text_content:setCascadeColorEnabled(true)
Text_content:setCascadeOpacityEnabled(true)
Text_content:setPosition(146.0337, 86.3925)
Text_content:setTextColor({r = 126, g = 110, b = 68})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_content)
layout:setPositionPercentX(0.4804)
layout:setPositionPercentY(0.2618)
layout:setPercentWidth(0.5362)
layout:setPercentHeight(0.1182)
layout:setSize({width = 163.0000, height = 39.0000})
layout:setLeftMargin(64.5337)
layout:setRightMargin(76.4663)
layout:setTopMargin(224.1075)
layout:setBottomMargin(66.8925)
Image_bg:addChild(Text_content)

--Create Image_buy
local Image_buy = ccui.ImageView:create()
Image_buy:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/store/store_plist.plist")
Image_buy:loadTexture("store_btn_buy_prop.png",1)
Image_buy:setTouchEnabled(true);
Image_buy:setLayoutComponentEnabled(true)
Image_buy:setName("Image_buy")
Image_buy:setTag(400)
Image_buy:setCascadeColorEnabled(true)
Image_buy:setCascadeOpacityEnabled(true)
Image_buy:setPosition(152.0374, 11.0183)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_buy)
layout:setPositionPercentX(0.5001)
layout:setPositionPercentY(0.0334)
layout:setPercentWidth(0.8717)
layout:setPercentHeight(0.2848)
layout:setSize({width = 265.0000, height = 94.0000})
layout:setLeftMargin(19.5374)
layout:setRightMargin(19.4626)
layout:setTopMargin(271.9817)
layout:setBottomMargin(-35.9817)
Image_bg:addChild(Image_buy)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

