--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1920.0000, height = 1080.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_bg:loadTexture("setting_bg.png",1)
Image_bg:setScale9Enabled(true)
Image_bg:setCapInsets({x = 343, y = 353, width = 354, height = 364})
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(87)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(1400.3560, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.7294)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5417)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1040.0000, height = 1080.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(880.3558)
layout:setRightMargin(-0.3558)
layout:setStretchHeightEnabled(true)
Layer:addChild(Image_bg)

--Create Image_header
local Image_header = ccui.ImageView:create()
Image_header:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_header:loadTexture("setting_top.png",1)
Image_header:setLayoutComponentEnabled(true)
Image_header:setName("Image_header")
Image_header:setTag(89)
Image_header:setCascadeColorEnabled(true)
Image_header:setCascadeOpacityEnabled(true)
Image_header:setPosition(519.4295, 1009.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_header)
layout:setPositionPercentX(0.4995)
layout:setPositionPercentY(0.9343)
layout:setPercentWidth(1.0144)
layout:setPercentHeight(0.1315)
layout:setSize({width = 1055.0000, height = 142.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(-8.0705)
layout:setRightMargin(-6.9294)
layout:setBottomMargin(938.0000)
Image_bg:addChild(Image_header)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("FZZhengHeiS-B-GB.ttf")
Text_title:setFontSize(52)
Text_title:setString([[购买方式]])
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(492)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(529.0568, 74.0952)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5015)
layout:setPositionPercentY(0.5218)
layout:setPercentWidth(0.1991)
layout:setPercentHeight(0.4507)
layout:setSize({width = 210.0000, height = 64.0000})
layout:setLeftMargin(424.0568)
layout:setRightMargin(420.9432)
layout:setTopMargin(35.9048)
layout:setBottomMargin(42.0952)
Image_header:addChild(Text_title)

--Create Image_content
local Image_content = ccui.ImageView:create()
Image_content:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common/hall_common.plist")
Image_content:loadTexture("setting_mask_bg.png",1)
Image_content:setScale9Enabled(true)
Image_content:setCapInsets({x = 45, y = 45, width = 12, height = 12})
Image_content:setTouchEnabled(true);
Image_content:setLayoutComponentEnabled(true)
Image_content:setName("Image_content")
Image_content:setTag(88)
Image_content:setCascadeColorEnabled(true)
Image_content:setCascadeOpacityEnabled(true)
Image_content:setPosition(518.9536, 476.4801)
Image_content:setScaleY(1.0127)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_content)
layout:setPositionPercentX(0.4990)
layout:setPositionPercentY(0.4412)
layout:setPercentWidth(0.9740)
layout:setPercentHeight(0.8225)
layout:setSize({width = 1013.0000, height = 888.3000})
layout:setVerticalEdge(1)
layout:setLeftMargin(12.4536)
layout:setRightMargin(14.5464)
layout:setTopMargin(159.3699)
layout:setBottomMargin(32.3301)
layout:setStretchHeightEnabled(true)
Image_bg:addChild(Image_content)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

