local KEYBOARD_MAX = 100
cc.exports.KEYBOARD_EVENTS = {
	KETBOARD_SCENE = KEYBOARD_MAX - 1,
	KETBOARD_POPLAYER = KEYBOARD_MAX - 2,
	KETBOARD_LOADING = KEYBOARD_MAX - 3,
	KETBOARD_POPDIALOG = KEYBOARD_MAX - 4,
}